{
 "title": "Clan Statistics",
 "time": { "from": "now-120d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "clans",
    "label": "Clans",
    "query": "select tag from league_war_clans\nunion select tag from war_clans\nunion select tag from clans\norder by tag"
   },
   {
    "name": "players",
    "label": "Players",
    "query": "select tag from league_war_clan_members\nunion select tag from war_clan_members\nunion select tag from members\norder by tag"
   },
   { "name": "warleagues", "label": "War Leagues", "query": "Yes,No" },
   { "name": "normalwars", "label": "Normal Wars", "query": "Yes,No" },
   { "name": "onlycurrentmembers", "label": "Only Current Members", "query": "Yes,No" }
  ]
 },
 "panels": [
  {
   "title": "Filters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Clans",
     "type": "table",
     "gridPos": { "h": 16, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "rawSql": "select\n\tlwc.name as 'Name',\n\tlwc.tag as 'Tag'\nfrom\n\tleague_wars lw\n\tjoin league_war_details lwd on lwd.league_war_id = lw.id\n\tjoin league_war_clans lwc on lwc.league_war_id = lw.id\nwhere\n\t$__timeFilter(lwd.end_time)\nunion\nselect\n\twc.name as 'Name',\n\twc.tag as 'Tag'\nfrom\n\twars w\n\tjoin war_clans wc on wc.war_id = w.id\nwhere\n\t$__timeFilter(w.end_time)\nunion\nselect\n\tc.name as 'Name',\n\tc.tag as 'Tag'\nfrom\n\trequests r\n\tjoin clans c on c.request_id = r.id\nwhere\n\t$__timeFilter(r.timestamp)\norder by\n\tName"
      }
     ]
    },
    {
     "title": "Players",
     "type": "table",
     "gridPos": { "h": 16, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "rawSql": "declare @latest_request_id int = (select top 1 id from requests order by timestamp desc)\r\ndeclare @latest_members table (tag nvarchar(16), name nvarchar(256))\r\ninsert into @latest_members\r\nselect\r\n\tm.tag,\r\n\tm.name\r\nfrom\r\n\trequests r\r\n\tjoin clans c on c.request_id = r.id\r\n\tjoin members m on m.clan_id = c.id\r\nwhere\r\n\tc.tag in ($clans)\r\n\tand r.id = @latest_request_id\r\n\r\nselect\r\n\tlwcm.name as 'Name',\r\n\tlwc.name as 'Clan',\r\n\tlwcm.tag as 'Tag'\r\nfrom\r\n\tleague_wars lw\r\n\tjoin league_war_details lwd on lwd.league_war_id = lw.id\r\n\tjoin league_war_clans lwc on lwc.league_war_id = lw.id\r\n\tjoin league_war_clan_members lwcm on lwcm.league_war_clan_id = lwc.id\r\nwhere\r\n\tlwc.tag in ($clans)\r\n\tand ('$onlycurrentmembers' = 'No' or lwcm.tag in (select tag from @latest_members))\r\n\tand $__timeFilter(lwd.end_time)\r\nunion\r\nselect\r\n\twcm.name as 'Name',\r\n\twc.name as 'Clan',\r\n\twcm.tag as 'Tag'\r\nfrom\r\n\twars w\r\n\tjoin war_clans wc on wc.war_id = w.id\r\n\tjoin war_clan_members wcm on wcm.war_clan_id = wc.id\r\nwhere\r\n\twc.tag in ($clans)\r\n\tand ('$onlycurrentmembers' = 'No' or wcm.tag in (select tag from @latest_members))\r\n\tand $__timeFilter(w.end_time)\r\nunion\r\nselect\r\n\tm.name as 'Name',\r\n\tc.name as 'Clan',\r\n\tm.tag as 'Tag'\r\nfrom\r\n\trequests r\r\n\tjoin clans c on c.request_id = r.id\r\n\tjoin members m on m.clan_id = c.id\r\nwhere\r\n\tc.tag in ($clans)\r\n\tand ('$onlycurrentmembers' = 'No' or m.tag in (select tag from @latest_members))\r\n\tand $__timeFilter(r.timestamp)\r\norder by\r\n\tName"
      }
     ]
    }
   ]
  },
  {
   "title": "War Participation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Table",
     "type": "table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "rawSql": "declare @latest_request_id int = (select top 1 id from requests order by timestamp desc)\r\ndeclare @latest_members table (tag nvarchar(16), name nvarchar(256))\r\ninsert into @latest_members\r\nselect\r\n\tm.tag,\r\n\tm.name\r\nfrom\r\n\trequests r\r\n\tjoin clans c on c.request_id = r.id\r\n\tjoin members m on m.clan_id = c.id\r\nwhere\r\n\tc.tag in ($clans)\r\n\tand m.tag in ($players)\r\n\tand r.id = @latest_request_id\r\n\r\ndeclare @attack_stats table (name nvarchar(256), tag nvarchar(16), clan nvarchar(256), clan_tag nvarchar(16), attacks_made int, attacks_available int, total_stars int, total_destruction int)\r\nif '$warleagues' = 'Yes' begin\r\n\tinsert into @attack_stats\r\n\tselect\r\n\t\tlwcm.name as name,\r\n\t\tlwcm.tag as tag,\r\n\t\tlwc.name as clan,\r\n\t\tlwc.tag as clan_tag,\r\n\t\tcount(lwcm.attack_attacker_tag) as attacks_made,\r\n\t\tcount(1) as attacks_available,\r\n\t\tsum(case when lwcm.attack_stars is not null then lwcm.attack_stars else 0 end) as total_stars,\r\n\t\tsum(case when lwcm.attack_destruction_percentage is not null then lwcm.attack_destruction_percentage else 0 end) as total_destruction\r\n\tfrom\r\n\t\tleague_wars lw\r\n\t\tjoin league_war_details lwd on lwd.league_war_id = lw.id\r\n\t\tjoin league_war_clans lwc on lwc.league_war_id = lw.id\r\n\t\tjoin league_war_clan_members lwcm on lwcm.league_war_clan_id = lwc.id\r\n\twhere\r\n\t\tlwc.tag in ($clans)\r\n\t\tand (lwcm.tag in (select tag from @latest_members) or '$onlycurrentmembers' = 'No' and lwcm.tag in ($players))\r\n\t\tand $__timeFilter(lwd.end_time)\r\n\tgroup by\r\n\t\tlwcm.name,\r\n\t\tlwcm.tag,\r\n\t\tlwc.name,\r\n\t\tlwc.tag\r\nend\r\nif '$normalwars' = 'Yes' begin\r\n\tdeclare @attacks_available table (tag nvarchar(16), attacks_available int)\r\n\tinsert into @attacks_available\r\n\tselect\r\n\t\twcm.tag,\r\n\t\tsum(w.attacks_per_member) attacks_available\r\n\tfrom\r\n\t\twars w\r\n\t\tjoin war_clans wc on wc.war_id = w.id\r\n\t\tjoin war_clan_members wcm on wcm.war_clan_id = wc.id\r\n\twhere\r\n\t\twc.tag in ($clans)\r\n\t\tand (wcm.tag in (select tag from @latest_members) or '$onlycurrentmembers' = 'No' and wcm.tag in ($players))\r\n\t\tand $__timeFilter(w.end_time)\r\n\tgroup by\r\n\t\twcm.tag\r\n\r\n\tinsert into @attack_stats\r\n\tselect\r\n\t\twcm.name as name,\r\n\t\twcm.tag as tag,\r\n\t\twc.name as clan,\r\n\t\twc.tag as clan_tag,\r\n\t\tcount(wa.attacker_tag) as attacks_made,\r\n\t\taa.attacks_available as attacks_available,\r\n\t\tsum(case when wa.stars is not null then wa.stars else 0 end) as total_stars,\r\n\t\tsum(case when wa.destruction_percentage is not null then wa.destruction_percentage else 0 end) as total_destruction\r\n\tfrom\r\n\t\twars w\r\n\t\tjoin war_clans wc on wc.war_id = w.id\r\n\t\tjoin war_clan_members wcm on wcm.war_clan_id = wc.id\r\n\t\tjoin @attacks_available aa on aa.tag = wcm.tag\r\n\t\tleft join war_attacks wa on wa.war_clan_member_id = wcm.id\r\n\twhere\r\n\t\t$__timeFilter(w.end_time)\r\n\tgroup by\r\n\t\twcm.name,\r\n\t\twcm.tag,\r\n\t\twc.name,\r\n\t\twc.tag,\r\n\t\taa.attacks_available\r\nend\r\n\r\nselect\r\n\tname as Name,\r\n\tclan as Clan,\r\n\tsum(attacks_made) / cast(sum(attacks_available) as float) as 'Attack Utilization',\r\n\tsum(attacks_made) as 'Attacks Made',\r\n\tsum(attacks_available) as 'Attacks Available',\r\n\tsum(total_stars) as 'Total Stars',\r\n\tsum(total_destruction) as 'Total Destruction'\r\nfrom\r\n\t@attack_stats\r\ngroup by\r\n\tname,\r\n\ttag,\r\n\tclan,\r\n\tclan_tag"
      }
     ]
    },
    {
     "title": "Attack Utilization",
     "type": "bargauge",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "declare @latest_request_id int = (select top 1 id from requests order by timestamp desc)\r\ndeclare @latest_members table (tag nvarchar(16), name nvarchar(256))\r\ninsert into @latest_members\r\nselect\r\n\tm.tag,\r\n\tm.name\r\nfrom\r\n\trequests r\r\n\tjoin clans c on c.request_id = r.id\r\n\tjoin members m on m.clan_id = c.id\r\nwhere\r\n\tc.tag in ($clans)\r\n\tand m.tag in ($players)\r\n\tand r.id = @latest_request_id\r\n\r\ndeclare @attack_stats table (name nvarchar(256), tag nvarchar(16), clan nvarchar(256), clan_tag nvarchar(16), attacks_made int, attacks_available int, total_stars int, total_destruction int)\r\nif '$warleagues' = 'Yes' begin\r\n\tinsert into @attack_stats\r\n\tselect\r\n\t\tlwcm.name as name,\r\n\t\tlwcm.tag as tag,\r\n\t\tlwc.name as clan,\r\n\t\tlwc.tag as clan_tag,\r\n\t\tcount(lwcm.attack_attacker_tag) as attacks_made,\r\n\t\tcount(1) as attacks_available,\r\n\t\tsum(case when lwcm.attack_stars is not null then lwcm.attack_stars else 0 end) as total_stars,\r\n\t\tsum(case when lwcm.attack_destruction_percentage is not null then lwcm.attack_destruction_percentage else 0 end) as total_destruction\r\n\tfrom\r\n\t\tleague_wars lw\r\n\t\tjoin league_war_details lwd on lwd.league_war_id = lw.id\r\n\t\tjoin league_war_clans lwc on lwc.league_war_id = lw.id\r\n\t\tjoin league_war_clan_members lwcm on lwcm.league_war_clan_id = lwc.id\r\n\twhere\r\n\t\tlwc.tag in ($clans)\r\n\t\tand (lwcm.tag in (select tag from @latest_members) or '$onlycurrentmembers' = 'No' and lwcm.tag in ($players))\r\n\t\tand $__timeFilter(lwd.end_time)\r\n\tgroup by\r\n\t\tlwcm.name,\r\n\t\tlwcm.tag,\r\n\t\tlwc.name,\r\n\t\tlwc.tag\r\nend\r\nif '$normalwars' = 'Yes' begin\r\n\tdeclare @attacks_available table (tag nvarchar(16), attacks_available int)\r\n\tinsert into @attacks_available\r\n\tselect\r\n\t\twcm.tag,\r\n\t\tsum(w.attacks_per_member) attacks_available\r\n\tfrom\r\n\t\twars w\r\n\t\tjoin war_clans wc on wc.war_id = w.id\r\n\t\tjoin war_clan_members wcm on wcm.war_clan_id = wc.id\r\n\twhere\r\n\t\twc.tag in ($clans)\r\n\t\tand (wcm.tag in (select tag from @latest_members) or '$onlycurrentmembers' = 'No' and wcm.tag in ($players))\r\n\t\tand $__timeFilter(w.end_time)\r\n\tgroup by\r\n\t\twcm.tag\r\n\r\n\tinsert into @attack_stats\r\n\tselect\r\n\t\twcm.name as name,\r\n\t\twcm.tag as tag,\r\n\t\twc.name as clan,\r\n\t\twc.tag as clan_tag,\r\n\t\tcount(wa.attacker_tag) as attacks_made,\r\n\t\taa.attacks_available as attacks_available,\r\n\t\tsum(case when wa.stars is not null then wa.stars else 0 end) as total_stars,\r\n\t\tsum(case when wa.destruction_percentage is not null then wa.destruction_percentage else 0 end) as total_destruction\r\n\tfrom\r\n\t\twars w\r\n\t\tjoin war_clans wc on wc.war_id = w.id\r\n\t\tjoin war_clan_members wcm on wcm.war_clan_id = wc.id\r\n\t\tjoin @attacks_available aa on aa.tag = wcm.tag\r\n\t\tleft join war_attacks wa on wa.war_clan_member_id = wcm.id\r\n\twhere\r\n\t\t$__timeFilter(w.end_time)\r\n\tgroup by\r\n\t\twcm.name,\r\n\t\twcm.tag,\r\n\t\twc.name,\r\n\t\twc.tag,\r\n\t\taa.attacks_available\r\nend\r\n\r\nselect\r\n\tname as Name,\r\n\tsum(attacks_made) / cast(sum(attacks_available) as float) as 'Attack Utilization'\r\nfrom\r\n\t@attack_stats\r\ngroup by\r\n\tname,\r\n\ttag,\r\n\tclan,\r\n\tclan_tag\r\norder by\r\n\tsum(attacks_made) / cast(sum(attacks_available) as float) desc"
      }
     ]
    },
    {
     "title": "Total Stars",
     "type": "bargauge",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "declare @latest_request_id int = (select top 1 id from requests order by timestamp desc)\r\ndeclare @latest_members table (tag nvarchar(16), name nvarchar(256))\r\ninsert into @latest_members\r\nselect\r\n\tm.tag,\r\n\tm.name\r\nfrom\r\n\trequests r\r\n\tjoin clans c on c.request_id = r.id\r\n\tjoin members m on m.clan_id = c.id\r\nwhere\r\n\tc.tag in ($clans)\r\n\tand m.tag in ($players)\r\n\tand r.id = @latest_request_id\r\n\r\ndeclare @attack_stats table (name nvarchar(256), tag nvarchar(16), clan nvarchar(256), clan_tag nvarchar(16), attacks_made int, attacks_available int, total_stars int, total_destruction int)\r\nif '$warleagues' = 'Yes' begin\r\n\tinsert into @attack_stats\r\n\tselect\r\n\t\tlwcm.name as name,\r\n\t\tlwcm.tag as tag,\r\n\t\tlwc.name as clan,\r\n\t\tlwc.tag as clan_tag,\r\n\t\tcount(lwcm.attack_attacker_tag) as attacks_made,\r\n\t\tcount(1) as attacks_available,\r\n\t\tsum(case when lwcm.attack_stars is not null then lwcm.attack_stars else 0 end) as total_stars,\r\n\t\tsum(case when lwcm.attack_destruction_percentage is not null then lwcm.attack_destruction_percentage else 0 end) as total_destruction\r\n\tfrom\r\n\t\tleague_wars lw\r\n\t\tjoin league_war_details lwd on lwd.league_war_id = lw.id\r\n\t\tjoin league_war_clans lwc on lwc.league_war_id = lw.id\r\n\t\tjoin league_war_clan_members lwcm on lwcm.league_war_clan_id = lwc.id\r\n\twhere\r\n\t\tlwc.tag in ($clans)\r\n\t\tand (lwcm.tag in (select tag from @latest_members) or '$onlycurrentmembers' = 'No' and lwcm.tag in ($players))\r\n\t\tand $__timeFilter(lwd.end_time)\r\n\tgroup by\r\n\t\tlwcm.name,\r\n\t\tlwcm.tag,\r\n\t\tlwc.name,\r\n\t\tlwc.tag\r\nend\r\nif '$normalwars' = 'Yes' begin\r\n\tdeclare @attacks_available table (tag nvarchar(16), attacks_available int)\r\n\tinsert into @attacks_available\r\n\tselect\r\n\t\twcm.tag,\r\n\t\tsum(w.attacks_per_member) attacks_available\r\n\tfrom\r\n\t\twars w\r\n\t\tjoin war_clans wc on wc.war_id = w.id\r\n\t\tjoin war_clan_members wcm on wcm.war_clan_id = wc.id\r\n\twhere\r\n\t\twc.tag in ($clans)\r\n\t\tand (wcm.tag in (select tag from @latest_members) or '$onlycurrentmembers' = 'No' and wcm.tag in ($players))\r\n\t\tand $__timeFilter(w.end_time)\r\n\tgroup by\r\n\t\twcm.tag\r\n\r\n\tinsert into @attack_stats\r\n\tselect\r\n\t\twcm.name as name,\r\n\t\twcm.tag as tag,\r\n\t\twc.name as clan,\r\n\t\twc.tag as clan_tag,\r\n\t\tcount(wa.attacker_tag) as attacks_made,\r\n\t\taa.attacks_available as attacks_available,\r\n\t\tsum(case when wa.stars is not null then wa.stars else 0 end) as total_stars,\r\n\t\tsum(case when wa.destruction_percentage is not null then wa.destruction_percentage else 0 end) as total_destruction\r\n\tfrom\r\n\t\twars w\r\n\t\tjoin war_clans wc on wc.war_id = w.id\r\n\t\tjoin war_clan_members wcm on wcm.war_clan_id = wc.id\r\n\t\tjoin @attacks_available aa on aa.tag = wcm.tag\r\n\t\tleft join war_attacks wa on wa.war_clan_member_id = wcm.id\r\n\twhere\r\n\t\t$__timeFilter(w.end_time)\r\n\tgroup by\r\n\t\twcm.name,\r\n\t\twcm.tag,\r\n\t\twc.name,\r\n\t\twc.tag,\r\n\t\taa.attacks_available\r\nend\r\n\r\nselect\r\n\tname as Name,\r\n\tsum(total_stars) as 'Total Stars'\r\nfrom\r\n\t@attack_stats\r\ngroup by\r\n\tname,\r\n\ttag,\r\n\tclan,\r\n\tclan_tag\r\norder by\r\n\tsum(total_stars) desc"
      }
     ]
    },
    {
     "title": "Total Destruction",
     "type": "bargauge",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "declare @latest_request_id int = (select top 1 id from requests order by timestamp desc)\r\ndeclare @latest_members table (tag nvarchar(16), name nvarchar(256))\r\ninsert into @latest_members\r\nselect\r\n\tm.tag,\r\n\tm.name\r\nfrom\r\n\trequests r\r\n\tjoin clans c on c.request_id = r.id\r\n\tjoin members m on m.clan_id = c.id\r\nwhere\r\n\tc.tag in ($clans)\r\n\tand m.tag in ($players)\r\n\tand r.id = @latest_request_id\r\n\r\ndeclare @attack_stats table (name nvarchar(256), tag nvarchar(16), clan nvarchar(256), clan_tag nvarchar(16), attacks_made int, attacks_available int, total_stars int, total_destruction int)\r\nif '$warleagues' = 'Yes' begin\r\n\tinsert into @attack_stats\r\n\tselect\r\n\t\tlwcm.name as name,\r\n\t\tlwcm.tag as tag,\r\n\t\tlwc.name as clan,\r\n\t\tlwc.tag as clan_tag,\r\n\t\tcount(lwcm.attack_attacker_tag) as attacks_made,\r\n\t\tcount(1) as attacks_available,\r\n\t\tsum(case when lwcm.attack_stars is not null then lwcm.attack_stars else 0 end) as total_stars,\r\n\t\tsum(case when lwcm.attack_destruction_percentage is not null then lwcm.attack_destruction_percentage else 0 end) as total_destruction\r\n\tfrom\r\n\t\tleague_wars lw\r\n\t\tjoin league_war_details lwd on lwd.league_war_id = lw.id\r\n\t\tjoin league_war_clans lwc on lwc.league_war_id = lw.id\r\n\t\tjoin league_war_clan_members lwcm on lwcm.league_war_clan_id = lwc.id\r\n\twhere\r\n\t\tlwc.tag in ($clans)\r\n\t\tand (lwcm.tag in (select tag from @latest_members) or '$onlycurrentmembers' = 'No' and lwcm.tag in ($players))\r\n\t\tand $__timeFilter(lwd.end_time)\r\n\tgroup by\r\n\t\tlwcm.name,\r\n\t\tlwcm.tag,\r\n\t\tlwc.name,\r\n\t\tlwc.tag\r\nend\r\nif '$normalwars' = 'Yes' begin\r\n\tdeclare @attacks_available table (tag nvarchar(16), attacks_available int)\r\n\tinsert into @attacks_available\r\n\tselect\r\n\t\twcm.tag,\r\n\t\tsum(w.attacks_per_member) attacks_available\r\n\tfrom\r\n\t\twars w\r\n\t\tjoin war_clans wc on wc.war_id = w.id\r\n\t\tjoin war_clan_members wcm on wcm.war_clan_id = wc.id\r\n\twhere\r\n\t\twc.tag in ($clans)\r\n\t\tand (wcm.tag in (select tag from @latest_members) or '$onlycurrentmembers' = 'No' and wcm.tag in ($players))\r\n\t\tand $__timeFilter(w.end_time)\r\n\tgroup by\r\n\t\twcm.tag\r\n\r\n\tinsert into @attack_stats\r\n\tselect\r\n\t\twcm.name as name,\r\n\t\twcm.tag as tag,\r\n\t\twc.name as clan,\r\n\t\twc.tag as clan_tag,\r\n\t\tcount(wa.attacker_tag) as attacks_made,\r\n\t\taa.attacks_available as attacks_available,\r\n\t\tsum(case when wa.stars is not null then wa.stars else 0 end) as total_stars,\r\n\t\tsum(case when wa.destruction_percentage is not null then wa.destruction_percentage else 0 end) as total_destruction\r\n\tfrom\r\n\t\twars w\r\n\t\tjoin war_clans wc on wc.war_id = w.id\r\n\t\tjoin war_clan_members wcm on wcm.war_clan_id = wc.id\r\n\t\tjoin @attacks_available aa on aa.tag = wcm.tag\r\n\t\tleft join war_attacks wa on wa.war_clan_member_id = wcm.id\r\n\twhere\r\n\t\t$__timeFilter(w.end_time)\r\n\tgroup by\r\n\t\twcm.name,\r\n\t\twcm.tag,\r\n\t\twc.name,\r\n\t\twc.tag,\r\n\t\taa.attacks_available\r\nend\r\n\r\nselect\r\n\tname as Name,\r\n\tsum(total_destruction) as 'Total Destruction'\r\nfrom\r\n\t@attack_stats\r\ngroup by\r\n\tname,\r\n\ttag,\r\n\tclan,\r\n\tclan_tag\r\norder by\r\n\tsum(total_destruction) desc"
      }
     ]
    }
   ]
  },
  {
   "title": "War Attacks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Table",
     "type": "table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "rawSql": "declare @latest_request_id int = (select top 1 id from requests order by timestamp desc)\r\ndeclare @latest_members table (tag nvarchar(16), name nvarchar(256))\r\ninsert into @latest_members\r\nselect\r\n\tm.tag,\r\n\tm.name\r\nfrom\r\n\trequests r\r\n\tjoin clans c on c.request_id = r.id\r\n\tjoin members m on m.clan_id = c.id\r\nwhere\r\n\tc.tag in ($clans)\r\n\tand r.id = @latest_request_id\r\n\r\ndeclare @attack_stats table (name nvarchar(256), tag nvarchar(16), clan nvarchar(256), clan_tag nvarchar(16), attacks_made int, total_stars int, total_destruction int, total_duration int, total_position int, total_enemy_position int, total_townhall int, total_enemy_townhall int)\r\nif '$warleagues' = 'Yes' begin\r\n\tdeclare @map_position table (clan_id int, member_id int, map_position int)\r\n\tinsert into @map_position\r\n\tselect\r\n\t\tlwc.id as clan_id,\r\n\t\tlwcm.id as member_id,\r\n\t\trow_number() over (partition by lwc.id order by lwcm.map_position) as map_position\r\n\tfrom\r\n\t\tleague_wars lw\r\n\t\tjoin league_war_details lwd on lwd.league_war_id = lw.id\r\n\t\tjoin league_war_clans lwc on lwc.league_war_id = lw.id\r\n\t\tjoin league_war_clan_members lwcm on lwcm.league_war_clan_id = lwc.id\r\n\twhere\r\n\t\t$__timeFilter(lwd.end_time)\r\n\r\n\tinsert into @attack_stats\r\n\tselect\r\n\t\tlwcm.name as name,\r\n\t\tlwcm.tag as tag,\r\n\t\tlwc.name as clan,\r\n\t\tlwc.tag as clan_tag,\r\n\t\tcount(lwcm.attack_attacker_tag) as attacks_made,\r\n\t\tsum(lwcm.attack_stars) as 'total_stars',\r\n\t\tsum(lwcm.attack_destruction_percentage) as 'total_destruction',\r\n\t\tsum(lwcm.attack_duration) as 'total_duration',\r\n\t\tsum(mp.map_position) as 'total_position',\r\n\t\tsum(mp2.map_position) as 'total_enemy_position',\r\n\t\tsum(lwcm.town_hall_level) as 'total_townhall',\r\n\t\tsum(lwcm2.town_hall_level) as 'total_enemy_townhall'\r\n\tfrom\r\n\t\tleague_wars lw\r\n\t\tjoin league_war_details lwd on lwd.league_war_id = lw.id\r\n\t\tjoin league_war_clans lwc on lwc.league_war_id = lw.id\r\n\t\tjoin league_war_clan_members lwcm on lwcm.league_war_clan_id = lwc.id\r\n\t\tjoin @map_position mp on mp.clan_id = lwc.id and mp.member_id = lwcm.id\r\n\t\tjoin league_war_clans lwc2 on lwc2.league_war_id = lw.id and lwc2.id <> lwc.id\r\n\t\tjoin league_war_clan_members lwcm2 on lwcm2.league_war_clan_id = lwc2.id and lwcm.attack_defender_tag = lwcm2.tag\r\n\t\tjoin @map_position mp2 on mp2.clan_id = lwc2.id and mp2.member_id = lwcm2.id\r\n\twhere\r\n\t\tlwc.tag in ($clans)\r\n\t\tand (lwcm.tag in (select tag from @latest_members) or '$onlycurrentmembers' = 'No' and lwcm.tag in ($players))\r\n\tgroup by\r\n\t\tlwcm.name,\r\n\t\tlwcm.tag,\r\n\t\tlwc.name,\r\n\t\tlwc.tag\r\nend\r\nif '$normalwars' = 'Yes' begin\r\n\tinsert into @attack_stats\r\n\tselect\r\n\t\twcm.name as name,\r\n\t\twcm.tag as tag,\r\n\t\twc.name as clan,\r\n\t\twc.tag as clan_tag,\r\n\t\tcount(1) as attacks_made,\r\n\t\tsum(wa.stars) as 'total_stars',\r\n\t\tsum(wa.destruction_percentage) as 'total_destruction',\r\n\t\tsum(wa.duration) as 'total_duration',\r\n\t\tsum(wcm.map_position) as 'total_position',\r\n\t\tsum(wcm2.map_position) as 'total_enemy_position',\r\n\t\tsum(wcm.town_hall_level) as 'total_townhall',\r\n\t\tsum(wcm2.town_hall_level) as 'total_enemy_townhall'\r\n\tfrom\r\n\t\twars w\r\n\t\tjoin war_clans wc on wc.war_id = w.id\r\n\t\tjoin war_clan_members wcm on wcm.war_clan_id = wc.id\r\n\t\tjoin war_attacks wa on wa.war_clan_member_id = wcm.id\r\n\t\tjoin war_clans wc2 on wc2.war_id = w.id and wc2.id <> wc.id\r\n\t\tjoin war_clan_members wcm2 on wcm2.war_clan_id = wc2.id and wa.defender_tag = wcm2.tag\r\n\twhere\r\n\t\twc.tag in ($clans)\r\n\t\tand (wcm.tag in (select tag from @latest_members) or '$onlycurrentmembers' = 'No' and wcm.tag in ($players))\r\n\t\tand $__timeFilter(w.end_time)\r\n\tgroup by\r\n\t\twcm.name,\r\n\t\twcm.tag,\r\n\t\twc.name,\r\n\t\twc.tag\r\nend\r\n\r\nselect\r\n\tname as 'Name',\r\n\tclan as 'Clan',\r\n\tsum(attacks_made) as 'Count',\r\n\tsum(total_destruction) / cast(sum(attacks_made) as float) as 'Destruction',\r\n\tsum(total_stars) / cast(sum(attacks_made) as float) as 'Stars',\r\n\tsum(total_duration) / cast(sum(attacks_made) as float) as 'Duration',\r\n\tsum(total_position) / cast(sum(attacks_made) as float) as 'Position',\r\n\tsum(total_enemy_position) / cast(sum(attacks_made) as float) as 'Enemy Position',\r\n\t(sum(total_enemy_position) - sum(total_position)) / cast(sum(attacks_made) as float) as 'Position Diff',\r\n\tsum(total_townhall) / cast(sum(attacks_made) as float) as 'Townhall',\r\n\tsum(total_enemy_townhall) / cast(sum(attacks_made) as float) as 'Enemy Townhall',\r\n\t(sum(total_enemy_townhall) - sum(total_townhall)) / cast(sum(attacks_made) as float) as 'Townhall Diff'\r\nfrom\r\n\t@attack_stats\r\ngroup by\r\n\tname,\r\n\ttag,\r\n\tclan,\r\n\tclan_tag"
      }
     ]
    },
    {
     "title": "Destruction",
     "type": "bargauge",
     "gridPos": { "h": 10, "w": 4, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "declare @latest_request_id int = (select top 1 id from requests order by timestamp desc)\r\ndeclare @latest_members table (tag nvarchar(16), name nvarchar(256))\r\ninsert into @latest_members\r\nselect\r\n\tm.tag,\r\n\tm.name\r\nfrom\r\n\trequests r\r\n\tjoin clans c on c.request_id = r.id\r\n\tjoin members m on m.clan_id = c.id\r\nwhere\r\n\tc.tag in ($clans)\r\n\tand r.id = @latest_request_id\r\n\r\ndeclare @attack_stats table (name nvarchar(256), tag nvarchar(16), clan nvarchar(256), clan_tag nvarchar(16), attacks_made int, total_stars int, total_destruction int, total_duration int, total_position int, total_enemy_position int, total_townhall int, total_enemy_townhall int)\r\nif '$warleagues' = 'Yes' begin\r\n\tdeclare @map_position table (clan_id int, member_id int, map_position int)\r\n\tinsert into @map_position\r\n\tselect\r\n\t\tlwc.id as clan_id,\r\n\t\tlwcm.id as member_id,\r\n\t\trow_number() over (partition by lwc.id order by lwcm.map_position) as map_position\r\n\tfrom\r\n\t\tleague_wars lw\r\n\t\tjoin league_war_details lwd on lwd.league_war_id = lw.id\r\n\t\tjoin league_war_clans lwc on lwc.league_war_id = lw.id\r\n\t\tjoin league_war_clan_members lwcm on lwcm.league_war_clan_id = lwc.id\r\n\twhere\r\n\t\t$__timeFilter(lwd.end_time)\r\n\r\n\tinsert into @attack_stats\r\n\tselect\r\n\t\tlwcm.name as name,\r\n\t\tlwcm.tag as tag,\r\n\t\tlwc.name as clan,\r\n\t\tlwc.tag as clan_tag,\r\n\t\tcount(lwcm.attack_attacker_tag) as attacks_made,\r\n\t\tsum(lwcm.attack_stars) as 'total_stars',\r\n\t\tsum(lwcm.attack_destruction_percentage) as 'total_destruction',\r\n\t\tsum(lwcm.attack_duration) as 'total_duration',\r\n\t\tsum(mp.map_position) as 'total_position',\r\n\t\tsum(mp2.map_position) as 'total_enemy_position',\r\n\t\tsum(lwcm.town_hall_level) as 'total_townhall',\r\n\t\tsum(lwcm2.town_hall_level) as 'total_enemy_townhall'\r\n\tfrom\r\n\t\tleague_wars lw\r\n\t\tjoin league_war_details lwd on lwd.league_war_id = lw.id\r\n\t\tjoin league_war_clans lwc on lwc.league_war_id = lw.id\r\n\t\tjoin league_war_clan_members lwcm on lwcm.league_war_clan_id = lwc.id\r\n\t\tjoin @map_position mp on mp.clan_id = lwc.id and mp.member_id = lwcm.id\r\n\t\tjoin league_war_clans lwc2 on lwc2.league_war_id = lw.id and lwc2.id <> lwc.id\r\n\t\tjoin league_war_clan_members lwcm2 on lwcm2.league_war_clan_id = lwc2.id and lwcm.attack_defender_tag = lwcm2.tag\r\n\t\tjoin @map_position mp2 on mp2.clan_id = lwc2.id and mp2.member_id = lwcm2.id\r\n\twhere\r\n\t\tlwc.tag in ($clans)\r\n\t\tand (lwcm.tag in (select tag from @latest_members) or '$onlycurrentmembers' = 'No' and lwcm.tag in ($players))\r\n\tgroup by\r\n\t\tlwcm.name,\r\n\t\tlwcm.tag,\r\n\t\tlwc.name,\r\n\t\tlwc.tag\r\nend\r\nif '$normalwars' = 'Yes' begin\r\n\tinsert into @attack_stats\r\n\tselect\r\n\t\twcm.name as name,\r\n\t\twcm.tag as tag,\r\n\t\twc.name as clan,\r\n\t\twc.tag as clan_tag,\r\n\t\tcount(1) as attacks_made,\r\n\t\tsum(wa.stars) as 'total_stars',\r\n\t\tsum(wa.destruction_percentage) as 'total_destruction',\r\n\t\tsum(wa.duration) as 'total_duration',\r\n\t\tsum(wcm.map_position) as 'total_position',\r\n\t\tsum(wcm2.map_position) as 'total_enemy_position',\r\n\t\tsum(wcm.town_hall_level) as 'total_townhall',\r\n\t\tsum(wcm2.town_hall_level) as 'total_enemy_townhall'\r\n\tfrom\r\n\t\twars w\r\n\t\tjoin war_clans wc on wc.war_id = w.id\r\n\t\tjoin war_clan_members wcm on wcm.war_clan_id = wc.id\r\n\t\tjoin war_attacks wa on wa.war_clan_member_id = wcm.id\r\n\t\tjoin war_clans wc2 on wc2.war_id = w.id and wc2.id <> wc.id\r\n\t\tjoin war_clan_members wcm2 on wcm2.war_clan_id = wc2.id and wa.defender_tag = wcm2.tag\r\n\twhere\r\n\t\twc.tag in ($clans)\r\n\t\tand (wcm.tag in (select tag from @latest_members) or '$onlycurrentmembers' = 'No' and wcm.tag in ($players))\r\n\t\tand $__timeFilter(w.end_time)\r\n\tgroup by\r\n\t\twcm.name,\r\n\t\twcm.tag,\r\n\t\twc.name,\r\n\t\twc.tag\r\nend\r\n\r\nselect\r\n\tname as 'Name',\r\n\tsum(total_destruction) / cast(sum(attacks_made) as float) as 'Destruction'\r\nfrom\r\n\t@attack_stats\r\ngroup by\r\n\tname,\r\n\ttag,\r\n\tclan,\r\n\tclan_tag\r\norder by\r\n\tsum(total_destruction) / cast(sum(attacks_made) as float) desc"
      }
     ]
    },
    {
     "title": "Stars",
     "type": "bargauge",
     "gridPos": { "h": 10, "w": 4, "x": 4, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "declare @latest_request_id int = (select top 1 id from requests order by timestamp desc)\r\ndeclare @latest_members table (tag nvarchar(16), name nvarchar(256))\r\ninsert into @latest_members\r\nselect\r\n\tm.tag,\r\n\tm.name\r\nfrom\r\n\trequests r\r\n\tjoin clans c on c.request_id = r.id\r\n\tjoin members m on m.clan_id = c.id\r\nwhere\r\n\tc.tag in ($clans)\r\n\tand r.id = @latest_request_id\r\n\r\ndeclare @attack_stats table (name nvarchar(256), tag nvarchar(16), clan nvarchar(256), clan_tag nvarchar(16), attacks_made int, total_stars int, total_destruction int, total_duration int, total_position int, total_enemy_position int, total_townhall int, total_enemy_townhall int)\r\nif '$warleagues' = 'Yes' begin\r\n\tdeclare @map_position table (clan_id int, member_id int, map_position int)\r\n\tinsert into @map_position\r\n\tselect\r\n\t\tlwc.id as clan_id,\r\n\t\tlwcm.id as member_id,\r\n\t\trow_number() over (partition by lwc.id order by lwcm.map_position) as map_position\r\n\tfrom\r\n\t\tleague_wars lw\r\n\t\tjoin league_war_details lwd on lwd.league_war_id = lw.id\r\n\t\tjoin league_war_clans lwc on lwc.league_war_id = lw.id\r\n\t\tjoin league_war_clan_members lwcm on lwcm.league_war_clan_id = lwc.id\r\n\twhere\r\n\t\t$__timeFilter(lwd.end_time)\r\n\r\n\tinsert into @attack_stats\r\n\tselect\r\n\t\tlwcm.name as name,\r\n\t\tlwcm.tag as tag,\r\n\t\tlwc.name as clan,\r\n\t\tlwc.tag as clan_tag,\r\n\t\tcount(lwcm.attack_attacker_tag) as attacks_made,\r\n\t\tsum(lwcm.attack_stars) as 'total_stars',\r\n\t\tsum(lwcm.attack_destruction_percentage) as 'total_destruction',\r\n\t\tsum(lwcm.attack_duration) as 'total_duration',\r\n\t\tsum(mp.map_position) as 'total_position',\r\n\t\tsum(mp2.map_position) as 'total_enemy_position',\r\n\t\tsum(lwcm.town_hall_level) as 'total_townhall',\r\n\t\tsum(lwcm2.town_hall_level) as 'total_enemy_townhall'\r\n\tfrom\r\n\t\tleague_wars lw\r\n\t\tjoin league_war_details lwd on lwd.league_war_id = lw.id\r\n\t\tjoin league_war_clans lwc on lwc.league_war_id = lw.id\r\n\t\tjoin league_war_clan_members lwcm on lwcm.league_war_clan_id = lwc.id\r\n\t\tjoin @map_position mp on mp.clan_id = lwc.id and mp.member_id = lwcm.id\r\n\t\tjoin league_war_clans lwc2 on lwc2.league_war_id = lw.id and lwc2.id <> lwc.id\r\n\t\tjoin league_war_clan_members lwcm2 on lwcm2.league_war_clan_id = lwc2.id and lwcm.attack_defender_tag = lwcm2.tag\r\n\t\tjoin @map_position mp2 on mp2.clan_id = lwc2.id and mp2.member_id = lwcm2.id\r\n\twhere\r\n\t\tlwc.tag in ($clans)\r\n\t\tand (lwcm.tag in (select tag from @latest_members) or '$onlycurrentmembers' = 'No' and lwcm.tag in ($players))\r\n\tgroup by\r\n\t\tlwcm.name,\r\n\t\tlwcm.tag,\r\n\t\tlwc.name,\r\n\t\tlwc.tag\r\nend\r\nif '$normalwars' = 'Yes' begin\r\n\tinsert into @attack_stats\r\n\tselect\r\n\t\twcm.name as name,\r\n\t\twcm.tag as tag,\r\n\t\twc.name as clan,\r\n\t\twc.tag as clan_tag,\r\n\t\tcount(1) as attacks_made,\r\n\t\tsum(wa.stars) as 'total_stars',\r\n\t\tsum(wa.destruction_percentage) as 'total_destruction',\r\n\t\tsum(wa.duration) as 'total_duration',\r\n\t\tsum(wcm.map_position) as 'total_position',\r\n\t\tsum(wcm2.map_position) as 'total_enemy_position',\r\n\t\tsum(wcm.town_hall_level) as 'total_townhall',\r\n\t\tsum(wcm2.town_hall_level) as 'total_enemy_townhall'\r\n\tfrom\r\n\t\twars w\r\n\t\tjoin war_clans wc on wc.war_id = w.id\r\n\t\tjoin war_clan_members wcm on wcm.war_clan_id = wc.id\r\n\t\tjoin war_attacks wa on wa.war_clan_member_id = wcm.id\r\n\t\tjoin war_clans wc2 on wc2.war_id = w.id and wc2.id <> wc.id\r\n\t\tjoin war_clan_members wcm2 on wcm2.war_clan_id = wc2.id and wa.defender_tag = wcm2.tag\r\n\twhere\r\n\t\twc.tag in ($clans)\r\n\t\tand (wcm.tag in (select tag from @latest_members) or '$onlycurrentmembers' = 'No' and wcm.tag in ($players))\r\n\t\tand $__timeFilter(w.end_time)\r\n\tgroup by\r\n\t\twcm.name,\r\n\t\twcm.tag,\r\n\t\twc.name,\r\n\t\twc.tag\r\nend\r\n\r\nselect\r\n\tname as 'Name',\r\n\tsum(total_stars) / cast(sum(attacks_made) as float) as 'Stars'\r\nfrom\r\n\t@attack_stats\r\ngroup by\r\n\tname,\r\n\ttag,\r\n\tclan,\r\n\tclan_tag\r\norder by\r\n\tsum(total_stars) / cast(sum(attacks_made) as float) desc"
      }
     ]
    },
    {
     "title": "Enemy Position",
     "type": "bargauge",
     "gridPos": { "h": 10, "w": 4, "x": 8, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "declare @latest_request_id int = (select top 1 id from requests order by timestamp desc)\r\ndeclare @latest_members table (tag nvarchar(16), name nvarchar(256))\r\ninsert into @latest_members\r\nselect\r\n\tm.tag,\r\n\tm.name\r\nfrom\r\n\trequests r\r\n\tjoin clans c on c.request_id = r.id\r\n\tjoin members m on m.clan_id = c.id\r\nwhere\r\n\tc.tag in ($clans)\r\n\tand r.id = @latest_request_id\r\n\r\ndeclare @attack_stats table (name nvarchar(256), tag nvarchar(16), clan nvarchar(256), clan_tag nvarchar(16), attacks_made int, total_stars int, total_destruction int, total_duration int, total_position int, total_enemy_position int, total_townhall int, total_enemy_townhall int)\r\nif '$warleagues' = 'Yes' begin\r\n\tdeclare @map_position table (clan_id int, member_id int, map_position int)\r\n\tinsert into @map_position\r\n\tselect\r\n\t\tlwc.id as clan_id,\r\n\t\tlwcm.id as member_id,\r\n\t\trow_number() over (partition by lwc.id order by lwcm.map_position) as map_position\r\n\tfrom\r\n\t\tleague_wars lw\r\n\t\tjoin league_war_details lwd on lwd.league_war_id = lw.id\r\n\t\tjoin league_war_clans lwc on lwc.league_war_id = lw.id\r\n\t\tjoin league_war_clan_members lwcm on lwcm.league_war_clan_id = lwc.id\r\n\twhere\r\n\t\t$__timeFilter(lwd.end_time)\r\n\r\n\tinsert into @attack_stats\r\n\tselect\r\n\t\tlwcm.name as name,\r\n\t\tlwcm.tag as tag,\r\n\t\tlwc.name as clan,\r\n\t\tlwc.tag as clan_tag,\r\n\t\tcount(lwcm.attack_attacker_tag) as attacks_made,\r\n\t\tsum(lwcm.attack_stars) as 'total_stars',\r\n\t\tsum(lwcm.attack_destruction_percentage) as 'total_destruction',\r\n\t\tsum(lwcm.attack_duration) as 'total_duration',\r\n\t\tsum(mp.map_position) as 'total_position',\r\n\t\tsum(mp2.map_position) as 'total_enemy_position',\r\n\t\tsum(lwcm.town_hall_level) as 'total_townhall',\r\n\t\tsum(lwcm2.town_hall_level) as 'total_enemy_townhall'\r\n\tfrom\r\n\t\tleague_wars lw\r\n\t\tjoin league_war_details lwd on lwd.league_war_id = lw.id\r\n\t\tjoin league_war_clans lwc on lwc.league_war_id = lw.id\r\n\t\tjoin league_war_clan_members lwcm on lwcm.league_war_clan_id = lwc.id\r\n\t\tjoin @map_position mp on mp.clan_id = lwc.id and mp.member_id = lwcm.id\r\n\t\tjoin league_war_clans lwc2 on lwc2.league_war_id = lw.id and lwc2.id <> lwc.id\r\n\t\tjoin league_war_clan_members lwcm2 on lwcm2.league_war_clan_id = lwc2.id and lwcm.attack_defender_tag = lwcm2.tag\r\n\t\tjoin @map_position mp2 on mp2.clan_id = lwc2.id and mp2.member_id = lwcm2.id\r\n\twhere\r\n\t\tlwc.tag in ($clans)\r\n\t\tand (lwcm.tag in (select tag from @latest_members) or '$onlycurrentmembers' = 'No' and lwcm.tag in ($players))\r\n\tgroup by\r\n\t\tlwcm.name,\r\n\t\tlwcm.tag,\r\n\t\tlwc.name,\r\n\t\tlwc.tag\r\nend\r\nif '$normalwars' = 'Yes' begin\r\n\tinsert into @attack_stats\r\n\tselect\r\n\t\twcm.name as name,\r\n\t\twcm.tag as tag,\r\n\t\twc.name as clan,\r\n\t\twc.tag as clan_tag,\r\n\t\tcount(1) as attacks_made,\r\n\t\tsum(wa.stars) as 'total_stars',\r\n\t\tsum(wa.destruction_percentage) as 'total_destruction',\r\n\t\tsum(wa.duration) as 'total_duration',\r\n\t\tsum(wcm.map_position) as 'total_position',\r\n\t\tsum(wcm2.map_position) as 'total_enemy_position',\r\n\t\tsum(wcm.town_hall_level) as 'total_townhall',\r\n\t\tsum(wcm2.town_hall_level) as 'total_enemy_townhall'\r\n\tfrom\r\n\t\twars w\r\n\t\tjoin war_clans wc on wc.war_id = w.id\r\n\t\tjoin war_clan_members wcm on wcm.war_clan_id = wc.id\r\n\t\tjoin war_attacks wa on wa.war_clan_member_id = wcm.id\r\n\t\tjoin war_clans wc2 on wc2.war_id = w.id and wc2.id <> wc.id\r\n\t\tjoin war_clan_members wcm2 on wcm2.war_clan_id = wc2.id and wa.defender_tag = wcm2.tag\r\n\twhere\r\n\t\twc.tag in ($clans)\r\n\t\tand (wcm.tag in (select tag from @latest_members) or '$onlycurrentmembers' = 'No' and wcm.tag in ($players))\r\n\t\tand $__timeFilter(w.end_time)\r\n\tgroup by\r\n\t\twcm.name,\r\n\t\twcm.tag,\r\n\t\twc.name,\r\n\t\twc.tag\r\nend\r\n\r\nselect\r\n\tname as 'Name',\r\n\tsum(total_enemy_position) / cast(sum(attacks_made) as float) as 'Enemy Position'\r\nfrom\r\n\t@attack_stats\r\ngroup by\r\n\tname,\r\n\ttag,\r\n\tclan,\r\n\tclan_tag\r\norder by\r\n\tsum(total_enemy_position) / cast(sum(attacks_made) as float) asc"
      }
     ]
    },
    {
     "title": "Position Diff",
     "type": "bargauge",
     "gridPos": { "h": 10, "w": 4, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "declare @latest_request_id int = (select top 1 id from requests order by timestamp desc)\r\ndeclare @latest_members table (tag nvarchar(16), name nvarchar(256))\r\ninsert into @latest_members\r\nselect\r\n\tm.tag,\r\n\tm.name\r\nfrom\r\n\trequests r\r\n\tjoin clans c on c.request_id = r.id\r\n\tjoin members m on m.clan_id = c.id\r\nwhere\r\n\tc.tag in ($clans)\r\n\tand r.id = @latest_request_id\r\n\r\ndeclare @attack_stats table (name nvarchar(256), tag nvarchar(16), clan nvarchar(256), clan_tag nvarchar(16), attacks_made int, total_stars int, total_destruction int, total_duration int, total_position int, total_enemy_position int, total_townhall int, total_enemy_townhall int)\r\nif '$warleagues' = 'Yes' begin\r\n\tdeclare @map_position table (clan_id int, member_id int, map_position int)\r\n\tinsert into @map_position\r\n\tselect\r\n\t\tlwc.id as clan_id,\r\n\t\tlwcm.id as member_id,\r\n\t\trow_number() over (partition by lwc.id order by lwcm.map_position) as map_position\r\n\tfrom\r\n\t\tleague_wars lw\r\n\t\tjoin league_war_details lwd on lwd.league_war_id = lw.id\r\n\t\tjoin league_war_clans lwc on lwc.league_war_id = lw.id\r\n\t\tjoin league_war_clan_members lwcm on lwcm.league_war_clan_id = lwc.id\r\n\twhere\r\n\t\t$__timeFilter(lwd.end_time)\r\n\r\n\tinsert into @attack_stats\r\n\tselect\r\n\t\tlwcm.name as name,\r\n\t\tlwcm.tag as tag,\r\n\t\tlwc.name as clan,\r\n\t\tlwc.tag as clan_tag,\r\n\t\tcount(lwcm.attack_attacker_tag) as attacks_made,\r\n\t\tsum(lwcm.attack_stars) as 'total_stars',\r\n\t\tsum(lwcm.attack_destruction_percentage) as 'total_destruction',\r\n\t\tsum(lwcm.attack_duration) as 'total_duration',\r\n\t\tsum(mp.map_position) as 'total_position',\r\n\t\tsum(mp2.map_position) as 'total_enemy_position',\r\n\t\tsum(lwcm.town_hall_level) as 'total_townhall',\r\n\t\tsum(lwcm2.town_hall_level) as 'total_enemy_townhall'\r\n\tfrom\r\n\t\tleague_wars lw\r\n\t\tjoin league_war_details lwd on lwd.league_war_id = lw.id\r\n\t\tjoin league_war_clans lwc on lwc.league_war_id = lw.id\r\n\t\tjoin league_war_clan_members lwcm on lwcm.league_war_clan_id = lwc.id\r\n\t\tjoin @map_position mp on mp.clan_id = lwc.id and mp.member_id = lwcm.id\r\n\t\tjoin league_war_clans lwc2 on lwc2.league_war_id = lw.id and lwc2.id <> lwc.id\r\n\t\tjoin league_war_clan_members lwcm2 on lwcm2.league_war_clan_id = lwc2.id and lwcm.attack_defender_tag = lwcm2.tag\r\n\t\tjoin @map_position mp2 on mp2.clan_id = lwc2.id and mp2.member_id = lwcm2.id\r\n\twhere\r\n\t\tlwc.tag in ($clans)\r\n\t\tand (lwcm.tag in (select tag from @latest_members) or '$onlycurrentmembers' = 'No' and lwcm.tag in ($players))\r\n\tgroup by\r\n\t\tlwcm.name,\r\n\t\tlwcm.tag,\r\n\t\tlwc.name,\r\n\t\tlwc.tag\r\nend\r\nif '$normalwars' = 'Yes' begin\r\n\tinsert into @attack_stats\r\n\tselect\r\n\t\twcm.name as name,\r\n\t\twcm.tag as tag,\r\n\t\twc.name as clan,\r\n\t\twc.tag as clan_tag,\r\n\t\tcount(1) as attacks_made,\r\n\t\tsum(wa.stars) as 'total_stars',\r\n\t\tsum(wa.destruction_percentage) as 'total_destruction',\r\n\t\tsum(wa.duration) as 'total_duration',\r\n\t\tsum(wcm.map_position) as 'total_position',\r\n\t\tsum(wcm2.map_position) as 'total_enemy_position',\r\n\t\tsum(wcm.town_hall_level) as 'total_townhall',\r\n\t\tsum(wcm2.town_hall_level) as 'total_enemy_townhall'\r\n\tfrom\r\n\t\twars w\r\n\t\tjoin war_clans wc on wc.war_id = w.id\r\n\t\tjoin war_clan_members wcm on wcm.war_clan_id = wc.id\r\n\t\tjoin war_attacks wa on wa.war_clan_member_id = wcm.id\r\n\t\tjoin war_clans wc2 on wc2.war_id = w.id and wc2.id <> wc.id\r\n\t\tjoin war_clan_members wcm2 on wcm2.war_clan_id = wc2.id and wa.defender_tag = wcm2.tag\r\n\twhere\r\n\t\twc.tag in ($clans)\r\n\t\tand (wcm.tag in (select tag from @latest_members) or '$onlycurrentmembers' = 'No' and wcm.tag in ($players))\r\n\t\tand $__timeFilter(w.end_time)\r\n\tgroup by\r\n\t\twcm.name,\r\n\t\twcm.tag,\r\n\t\twc.name,\r\n\t\twc.tag\r\nend\r\n\r\nselect\r\n\tname as 'Name',\r\n\t(sum(total_enemy_position) - sum(total_position)) / cast(sum(attacks_made) as float) as 'Position Diff'\r\nfrom\r\n\t@attack_stats\r\ngroup by\r\n\tname,\r\n\ttag,\r\n\tclan,\r\n\tclan_tag\r\norder by\r\n\t(sum(total_enemy_position) - sum(total_position)) / cast(sum(attacks_made) as float) asc"
      }
     ]
    },
    {
     "title": "Enemy Townhall",
     "type": "bargauge",
     "gridPos": { "h": 10, "w": 4, "x": 16, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "declare @latest_request_id int = (select top 1 id from requests order by timestamp desc)\r\ndeclare @latest_members table (tag nvarchar(16), name nvarchar(256))\r\ninsert into @latest_members\r\nselect\r\n\tm.tag,\r\n\tm.name\r\nfrom\r\n\trequests r\r\n\tjoin clans c on c.request_id = r.id\r\n\tjoin members m on m.clan_id = c.id\r\nwhere\r\n\tc.tag in ($clans)\r\n\tand r.id = @latest_request_id\r\n\r\ndeclare @attack_stats table (name nvarchar(256), tag nvarchar(16), clan nvarchar(256), clan_tag nvarchar(16), attacks_made int, total_stars int, total_destruction int, total_duration int, total_position int, total_enemy_position int, total_townhall int, total_enemy_townhall int)\r\nif '$warleagues' = 'Yes' begin\r\n\tdeclare @map_position table (clan_id int, member_id int, map_position int)\r\n\tinsert into @map_position\r\n\tselect\r\n\t\tlwc.id as clan_id,\r\n\t\tlwcm.id as member_id,\r\n\t\trow_number() over (partition by lwc.id order by lwcm.map_position) as map_position\r\n\tfrom\r\n\t\tleague_wars lw\r\n\t\tjoin league_war_details lwd on lwd.league_war_id = lw.id\r\n\t\tjoin league_war_clans lwc on lwc.league_war_id = lw.id\r\n\t\tjoin league_war_clan_members lwcm on lwcm.league_war_clan_id = lwc.id\r\n\twhere\r\n\t\t$__timeFilter(lwd.end_time)\r\n\r\n\tinsert into @attack_stats\r\n\tselect\r\n\t\tlwcm.name as name,\r\n\t\tlwcm.tag as tag,\r\n\t\tlwc.name as clan,\r\n\t\tlwc.tag as clan_tag,\r\n\t\tcount(lwcm.attack_attacker_tag) as attacks_made,\r\n\t\tsum(lwcm.attack_stars) as 'total_stars',\r\n\t\tsum(lwcm.attack_destruction_percentage) as 'total_destruction',\r\n\t\tsum(lwcm.attack_duration) as 'total_duration',\r\n\t\tsum(mp.map_position) as 'total_position',\r\n\t\tsum(mp2.map_position) as 'total_enemy_position',\r\n\t\tsum(lwcm.town_hall_level) as 'total_townhall',\r\n\t\tsum(lwcm2.town_hall_level) as 'total_enemy_townhall'\r\n\tfrom\r\n\t\tleague_wars lw\r\n\t\tjoin league_war_details lwd on lwd.league_war_id = lw.id\r\n\t\tjoin league_war_clans lwc on lwc.league_war_id = lw.id\r\n\t\tjoin league_war_clan_members lwcm on lwcm.league_war_clan_id = lwc.id\r\n\t\tjoin @map_position mp on mp.clan_id = lwc.id and mp.member_id = lwcm.id\r\n\t\tjoin league_war_clans lwc2 on lwc2.league_war_id = lw.id and lwc2.id <> lwc.id\r\n\t\tjoin league_war_clan_members lwcm2 on lwcm2.league_war_clan_id = lwc2.id and lwcm.attack_defender_tag = lwcm2.tag\r\n\t\tjoin @map_position mp2 on mp2.clan_id = lwc2.id and mp2.member_id = lwcm2.id\r\n\twhere\r\n\t\tlwc.tag in ($clans)\r\n\t\tand (lwcm.tag in (select tag from @latest_members) or '$onlycurrentmembers' = 'No' and lwcm.tag in ($players))\r\n\tgroup by\r\n\t\tlwcm.name,\r\n\t\tlwcm.tag,\r\n\t\tlwc.name,\r\n\t\tlwc.tag\r\nend\r\nif '$normalwars' = 'Yes' begin\r\n\tinsert into @attack_stats\r\n\tselect\r\n\t\twcm.name as name,\r\n\t\twcm.tag as tag,\r\n\t\twc.name as clan,\r\n\t\twc.tag as clan_tag,\r\n\t\tcount(1) as attacks_made,\r\n\t\tsum(wa.stars) as 'total_stars',\r\n\t\tsum(wa.destruction_percentage) as 'total_destruction',\r\n\t\tsum(wa.duration) as 'total_duration',\r\n\t\tsum(wcm.map_position) as 'total_position',\r\n\t\tsum(wcm2.map_position) as 'total_enemy_position',\r\n\t\tsum(wcm.town_hall_level) as 'total_townhall',\r\n\t\tsum(wcm2.town_hall_level) as 'total_enemy_townhall'\r\n\tfrom\r\n\t\twars w\r\n\t\tjoin war_clans wc on wc.war_id = w.id\r\n\t\tjoin war_clan_members wcm on wcm.war_clan_id = wc.id\r\n\t\tjoin war_attacks wa on wa.war_clan_member_id = wcm.id\r\n\t\tjoin war_clans wc2 on wc2.war_id = w.id and wc2.id <> wc.id\r\n\t\tjoin war_clan_members wcm2 on wcm2.war_clan_id = wc2.id and wa.defender_tag = wcm2.tag\r\n\twhere\r\n\t\twc.tag in ($clans)\r\n\t\tand (wcm.tag in (select tag from @latest_members) or '$onlycurrentmembers' = 'No' and wcm.tag in ($players))\r\n\t\tand $__timeFilter(w.end_time)\r\n\tgroup by\r\n\t\twcm.name,\r\n\t\twcm.tag,\r\n\t\twc.name,\r\n\t\twc.tag\r\nend\r\n\r\nselect\r\n\tname as 'Name',\r\n\tsum(total_enemy_townhall) / cast(sum(attacks_made) as float) as 'Enemy Townhall'\r\nfrom\r\n\t@attack_stats\r\ngroup by\r\n\tname,\r\n\ttag,\r\n\tclan,\r\n\tclan_tag\r\norder by\r\n\tsum(total_enemy_townhall) / cast(sum(attacks_made) as float) desc"
      }
     ]
    },
    {
     "title": "Townhall diff",
     "type": "bargauge",
     "gridPos": { "h": 10, "w": 4, "x": 20, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "declare @latest_request_id int = (select top 1 id from requests order by timestamp desc)\r\ndeclare @latest_members table (tag nvarchar(16), name nvarchar(256))\r\ninsert into @latest_members\r\nselect\r\n\tm.tag,\r\n\tm.name\r\nfrom\r\n\trequests r\r\n\tjoin clans c on c.request_id = r.id\r\n\tjoin members m on m.clan_id = c.id\r\nwhere\r\n\tc.tag in ($clans)\r\n\tand r.id = @latest_request_id\r\n\r\ndeclare @attack_stats table (name nvarchar(256), tag nvarchar(16), clan nvarchar(256), clan_tag nvarchar(16), attacks_made int, total_stars int, total_destruction int, total_duration int, total_position int, total_enemy_position int, total_townhall int, total_enemy_townhall int)\r\nif '$warleagues' = 'Yes' begin\r\n\tdeclare @map_position table (clan_id int, member_id int, map_position int)\r\n\tinsert into @map_position\r\n\tselect\r\n\t\tlwc.id as clan_id,\r\n\t\tlwcm.id as member_id,\r\n\t\trow_number() over (partition by lwc.id order by lwcm.map_position) as map_position\r\n\tfrom\r\n\t\tleague_wars lw\r\n\t\tjoin league_war_details lwd on lwd.league_war_id = lw.id\r\n\t\tjoin league_war_clans lwc on lwc.league_war_id = lw.id\r\n\t\tjoin league_war_clan_members lwcm on lwcm.league_war_clan_id = lwc.id\r\n\twhere\r\n\t\t$__timeFilter(lwd.end_time)\r\n\r\n\tinsert into @attack_stats\r\n\tselect\r\n\t\tlwcm.name as name,\r\n\t\tlwcm.tag as tag,\r\n\t\tlwc.name as clan,\r\n\t\tlwc.tag as clan_tag,\r\n\t\tcount(lwcm.attack_attacker_tag) as attacks_made,\r\n\t\tsum(lwcm.attack_stars) as 'total_stars',\r\n\t\tsum(lwcm.attack_destruction_percentage) as 'total_destruction',\r\n\t\tsum(lwcm.attack_duration) as 'total_duration',\r\n\t\tsum(mp.map_position) as 'total_position',\r\n\t\tsum(mp2.map_position) as 'total_enemy_position',\r\n\t\tsum(lwcm.town_hall_level) as 'total_townhall',\r\n\t\tsum(lwcm2.town_hall_level) as 'total_enemy_townhall'\r\n\tfrom\r\n\t\tleague_wars lw\r\n\t\tjoin league_war_details lwd on lwd.league_war_id = lw.id\r\n\t\tjoin league_war_clans lwc on lwc.league_war_id = lw.id\r\n\t\tjoin league_war_clan_members lwcm on lwcm.league_war_clan_id = lwc.id\r\n\t\tjoin @map_position mp on mp.clan_id = lwc.id and mp.member_id = lwcm.id\r\n\t\tjoin league_war_clans lwc2 on lwc2.league_war_id = lw.id and lwc2.id <> lwc.id\r\n\t\tjoin league_war_clan_members lwcm2 on lwcm2.league_war_clan_id = lwc2.id and lwcm.attack_defender_tag = lwcm2.tag\r\n\t\tjoin @map_position mp2 on mp2.clan_id = lwc2.id and mp2.member_id = lwcm2.id\r\n\twhere\r\n\t\tlwc.tag in ($clans)\r\n\t\tand (lwcm.tag in (select tag from @latest_members) or '$onlycurrentmembers' = 'No' and lwcm.tag in ($players))\r\n\tgroup by\r\n\t\tlwcm.name,\r\n\t\tlwcm.tag,\r\n\t\tlwc.name,\r\n\t\tlwc.tag\r\nend\r\nif '$normalwars' = 'Yes' begin\r\n\tinsert into @attack_stats\r\n\tselect\r\n\t\twcm.name as name,\r\n\t\twcm.tag as tag,\r\n\t\twc.name as clan,\r\n\t\twc.tag as clan_tag,\r\n\t\tcount(1) as attacks_made,\r\n\t\tsum(wa.stars) as 'total_stars',\r\n\t\tsum(wa.destruction_percentage) as 'total_destruction',\r\n\t\tsum(wa.duration) as 'total_duration',\r\n\t\tsum(wcm.map_position) as 'total_position',\r\n\t\tsum(wcm2.map_position) as 'total_enemy_position',\r\n\t\tsum(wcm.town_hall_level) as 'total_townhall',\r\n\t\tsum(wcm2.town_hall_level) as 'total_enemy_townhall'\r\n\tfrom\r\n\t\twars w\r\n\t\tjoin war_clans wc on wc.war_id = w.id\r\n\t\tjoin war_clan_members wcm on wcm.war_clan_id = wc.id\r\n\t\tjoin war_attacks wa on wa.war_clan_member_id = wcm.id\r\n\t\tjoin war_clans wc2 on wc2.war_id = w.id and wc2.id <> wc.id\r\n\t\tjoin war_clan_members wcm2 on wcm2.war_clan_id = wc2.id and wa.defender_tag = wcm2.tag\r\n\twhere\r\n\t\twc.tag in ($clans)\r\n\t\tand (wcm.tag in (select tag from @latest_members) or '$onlycurrentmembers' = 'No' and wcm.tag in ($players))\r\n\t\tand $__timeFilter(w.end_time)\r\n\tgroup by\r\n\t\twcm.name,\r\n\t\twcm.tag,\r\n\t\twc.name,\r\n\t\twc.tag\r\nend\r\n\r\nselect\r\n\tname as 'Name',\r\n\t(sum(total_enemy_townhall) - sum(total_townhall)) / cast(sum(attacks_made) as float) as 'Townhall Diff'\r\nfrom\r\n\t@attack_stats\r\ngroup by\r\n\tname,\r\n\ttag,\r\n\tclan,\r\n\tclan_tag\r\norder by\r\n\t(sum(total_enemy_townhall) - sum(total_townhall)) / cast(sum(attacks_made) as float) desc"
      }
     ]
    }
   ]
  },
  {
   "title": "War Defenses",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Table",
     "type": "table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "rawSql": "declare @latest_request_id int = (select top 1 id from requests order by timestamp desc)\r\ndeclare @latest_members table (tag nvarchar(16), name nvarchar(256))\r\ninsert into @latest_members\r\nselect\r\n\tm.tag,\r\n\tm.name\r\nfrom\r\n\trequests r\r\n\tjoin clans c on c.request_id = r.id\r\n\tjoin members m on m.clan_id = c.id\r\nwhere\r\n\tc.tag in ($clans)\r\n\tand m.tag in ($players)\r\n\tand r.id = @latest_request_id\r\n\t\r\ndeclare @attack_stats table (name nvarchar(256), tag nvarchar(16), clan nvarchar(256), clan_tag nvarchar(16), attacks_made int, total_stars int, total_destruction int, total_duration int, total_position int, total_enemy_position int, total_townhall int, total_enemy_townhall int)\r\nif '$warleagues' = 'Yes' begin\r\n\tdeclare @map_position table (clan_id int, member_id int, map_position int)\r\n\tinsert into @map_position\r\n\tselect\r\n\t\tlwc.id as clan_id,\r\n\t\tlwcm.id as member_id,\r\n\t\trow_number() over (partition by lwc.id order by lwcm.map_position) as map_position\r\n\tfrom\r\n\t\tleague_wars lw\r\n\t\tjoin league_war_details lwd on lwd.league_war_id = lw.id\r\n\t\tjoin league_war_clans lwc on lwc.league_war_id = lw.id\r\n\t\tjoin league_war_clan_members lwcm on lwcm.league_war_clan_id = lwc.id\r\n\twhere\r\n\t\t$__timeFilter(lwd.end_time)\r\n\r\n\tinsert into @attack_stats\r\n\tselect\r\n\t\tlwcm2.name as name,\r\n\t\tlwcm2.tag as tag,\r\n\t\tlwc2.name as clan,\r\n\t\tlwc2.tag as clan_tag,\r\n\t\tcount(lwcm.attack_attacker_tag) as attacks_made,\r\n\t\tsum(lwcm.attack_stars) as 'total_stars',\r\n\t\tsum(lwcm.attack_destruction_percentage) as 'total_destruction',\r\n\t\tsum(lwcm.attack_duration) as 'total_duration',\r\n\t\tsum(mp2.map_position) as 'total_position',\r\n\t\tsum(mp.map_position) as 'total_enemy_position',\r\n\t\tsum(lwcm2.town_hall_level) as 'total_townhall',\r\n\t\tsum(lwcm.town_hall_level) as 'total_enemy_townhall'\r\n\tfrom\r\n\t\tleague_wars lw\r\n\t\tjoin league_war_details lwd on lwd.league_war_id = lw.id\r\n\t\tjoin league_war_clans lwc on lwc.league_war_id = lw.id\r\n\t\tjoin league_war_clan_members lwcm on lwcm.league_war_clan_id = lwc.id\r\n\t\tjoin @map_position mp on mp.clan_id = lwc.id and mp.member_id = lwcm.id\r\n\t\tjoin league_war_clans lwc2 on lwc2.league_war_id = lw.id and lwc2.id <> lwc.id\r\n\t\tjoin league_war_clan_members lwcm2 on lwcm2.league_war_clan_id = lwc2.id and lwcm.attack_defender_tag = lwcm2.tag\r\n\t\tjoin @map_position mp2 on mp2.clan_id = lwc2.id and mp2.member_id = lwcm2.id\r\n\twhere\r\n\t\tlwc2.tag in ($clans)\r\n\t\tand (lwcm2.tag in (select tag from @latest_members) or '$onlycurrentmembers' = 'No' and lwcm2.tag in ($players))\r\n\tgroup by\r\n\t\tlwcm2.name,\r\n\t\tlwcm2.tag,\r\n\t\tlwc2.name,\r\n\t\tlwc2.tag\r\nend\r\nif '$normalwars' = 'Yes' begin\r\n\tinsert into @attack_stats\r\n\tselect\r\n\t\twcm2.name as name,\r\n\t\twcm2.tag as tag,\r\n\t\twc2.name as clan,\r\n\t\twc2.tag as clan_tag,\r\n\t\tcount(1) as attacks_made,\r\n\t\tsum(wa.stars) as 'total_stars',\r\n\t\tsum(wa.destruction_percentage) as 'total_destruction',\r\n\t\tsum(wa.duration) as 'total_duration',\r\n\t\tsum(wcm2.map_position) as 'total_position',\r\n\t\tsum(wcm.map_position) as 'total_enemy_position',\r\n\t\tsum(wcm2.town_hall_level) as 'total_townhall',\r\n\t\tsum(wcm.town_hall_level) as 'total_enemy_townhall'\r\n\tfrom\r\n\t\twars w\r\n\t\tjoin war_clans wc on wc.war_id = w.id\r\n\t\tjoin war_clan_members wcm on wcm.war_clan_id = wc.id\r\n\t\tjoin war_attacks wa on wa.war_clan_member_id = wcm.id\r\n\t\tjoin war_clans wc2 on wc2.war_id = w.id and wc2.id <> wc.id\r\n\t\tjoin war_clan_members wcm2 on wcm2.war_clan_id = wc2.id and wa.defender_tag = wcm2.tag\r\n\twhere\r\n\t\twc2.tag in ($clans)\r\n\t\tand (wcm2.tag in (select tag from @latest_members) or '$onlycurrentmembers' = 'No' and wcm2.tag in ($players))\r\n\t\tand $__timeFilter(w.end_time)\r\n\tgroup by\r\n\t\twcm2.name,\r\n\t\twcm2.tag,\r\n\t\twc2.name,\r\n\t\twc2.tag\r\nend\r\n\r\nselect\r\n\tname as 'Name',\r\n\tclan as 'Clan',\r\n\tsum(attacks_made) as 'Count',\r\n\tsum(total_destruction) / cast(sum(attacks_made) as float) as 'Destruction',\r\n\tsum(total_stars) / cast(sum(attacks_made) as float) as 'Stars',\r\n\tsum(total_duration) / cast(sum(attacks_made) as float) as 'Duration',\r\n\tsum(total_position) / cast(sum(attacks_made) as float) as 'Position',\r\n\tsum(total_enemy_position) / cast(sum(attacks_made) as float) as 'Enemy Position',\r\n\t(sum(total_enemy_position) - sum(total_position)) / cast(sum(attacks_made) as float) as 'Position Diff',\r\n\tsum(total_townhall) / cast(sum(attacks_made) as float) as 'Townhall',\r\n\tsum(total_enemy_townhall) / cast(sum(attacks_made) as float) as 'Enemy Townhall',\r\n\t(sum(total_enemy_townhall) - sum(total_townhall)) / cast(sum(attacks_made) as float) as 'Townhall Diff'\r\nfrom\r\n\t@attack_stats\r\ngroup by\r\n\tname,\r\n\ttag,\r\n\tclan,\r\n\tclan_tag"
      }
     ]
    },
    {
     "title": "Destruction",
     "type": "bargauge",
     "gridPos": { "h": 10, "w": 4, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "declare @latest_request_id int = (select top 1 id from requests order by timestamp desc)\r\ndeclare @latest_members table (tag nvarchar(16), name nvarchar(256))\r\ninsert into @latest_members\r\nselect\r\n\tm.tag,\r\n\tm.name\r\nfrom\r\n\trequests r\r\n\tjoin clans c on c.request_id = r.id\r\n\tjoin members m on m.clan_id = c.id\r\nwhere\r\n\tc.tag in ($clans)\r\n\tand m.tag in ($players)\r\n\tand r.id = @latest_request_id\r\n\t\r\ndeclare @attack_stats table (name nvarchar(256), tag nvarchar(16), clan nvarchar(256), clan_tag nvarchar(16), attacks_made int, total_stars int, total_destruction int, total_duration int, total_position int, total_enemy_position int, total_townhall int, total_enemy_townhall int)\r\nif '$warleagues' = 'Yes' begin\r\n\tdeclare @map_position table (clan_id int, member_id int, map_position int)\r\n\tinsert into @map_position\r\n\tselect\r\n\t\tlwc.id as clan_id,\r\n\t\tlwcm.id as member_id,\r\n\t\trow_number() over (partition by lwc.id order by lwcm.map_position) as map_position\r\n\tfrom\r\n\t\tleague_wars lw\r\n\t\tjoin league_war_details lwd on lwd.league_war_id = lw.id\r\n\t\tjoin league_war_clans lwc on lwc.league_war_id = lw.id\r\n\t\tjoin league_war_clan_members lwcm on lwcm.league_war_clan_id = lwc.id\r\n\twhere\r\n\t\t$__timeFilter(lwd.end_time)\r\n\r\n\tinsert into @attack_stats\r\n\tselect\r\n\t\tlwcm2.name as name,\r\n\t\tlwcm2.tag as tag,\r\n\t\tlwc2.name as clan,\r\n\t\tlwc2.tag as clan_tag,\r\n\t\tcount(lwcm.attack_attacker_tag) as attacks_made,\r\n\t\tsum(lwcm.attack_stars) as 'total_stars',\r\n\t\tsum(lwcm.attack_destruction_percentage) as 'total_destruction',\r\n\t\tsum(lwcm.attack_duration) as 'total_duration',\r\n\t\tsum(mp2.map_position) as 'total_position',\r\n\t\tsum(mp.map_position) as 'total_enemy_position',\r\n\t\tsum(lwcm2.town_hall_level) as 'total_townhall',\r\n\t\tsum(lwcm.town_hall_level) as 'total_enemy_townhall'\r\n\tfrom\r\n\t\tleague_wars lw\r\n\t\tjoin league_war_details lwd on lwd.league_war_id = lw.id\r\n\t\tjoin league_war_clans lwc on lwc.league_war_id = lw.id\r\n\t\tjoin league_war_clan_members lwcm on lwcm.league_war_clan_id = lwc.id\r\n\t\tjoin @map_position mp on mp.clan_id = lwc.id and mp.member_id = lwcm.id\r\n\t\tjoin league_war_clans lwc2 on lwc2.league_war_id = lw.id and lwc2.id <> lwc.id\r\n\t\tjoin league_war_clan_members lwcm2 on lwcm2.league_war_clan_id = lwc2.id and lwcm.attack_defender_tag = lwcm2.tag\r\n\t\tjoin @map_position mp2 on mp2.clan_id = lwc2.id and mp2.member_id = lwcm2.id\r\n\twhere\r\n\t\tlwc2.tag in ($clans)\r\n\t\tand (lwcm2.tag in (select tag from @latest_members) or '$onlycurrentmembers' = 'No' and lwcm2.tag in ($players))\r\n\tgroup by\r\n\t\tlwcm2.name,\r\n\t\tlwcm2.tag,\r\n\t\tlwc2.name,\r\n\t\tlwc2.tag\r\nend\r\nif '$normalwars' = 'Yes' begin\r\n\tinsert into @attack_stats\r\n\tselect\r\n\t\twcm2.name as name,\r\n\t\twcm2.tag as tag,\r\n\t\twc2.name as clan,\r\n\t\twc2.tag as clan_tag,\r\n\t\tcount(1) as attacks_made,\r\n\t\tsum(wa.stars) as 'total_stars',\r\n\t\tsum(wa.destruction_percentage) as 'total_destruction',\r\n\t\tsum(wa.duration) as 'total_duration',\r\n\t\tsum(wcm2.map_position) as 'total_position',\r\n\t\tsum(wcm.map_position) as 'total_enemy_position',\r\n\t\tsum(wcm2.town_hall_level) as 'total_townhall',\r\n\t\tsum(wcm.town_hall_level) as 'total_enemy_townhall'\r\n\tfrom\r\n\t\twars w\r\n\t\tjoin war_clans wc on wc.war_id = w.id\r\n\t\tjoin war_clan_members wcm on wcm.war_clan_id = wc.id\r\n\t\tjoin war_attacks wa on wa.war_clan_member_id = wcm.id\r\n\t\tjoin war_clans wc2 on wc2.war_id = w.id and wc2.id <> wc.id\r\n\t\tjoin war_clan_members wcm2 on wcm2.war_clan_id = wc2.id and wa.defender_tag = wcm2.tag\r\n\twhere\r\n\t\twc2.tag in ($clans)\r\n\t\tand (wcm2.tag in (select tag from @latest_members) or '$onlycurrentmembers' = 'No' and wcm2.tag in ($players))\r\n\t\tand $__timeFilter(w.end_time)\r\n\tgroup by\r\n\t\twcm2.name,\r\n\t\twcm2.tag,\r\n\t\twc2.name,\r\n\t\twc2.tag\r\nend\r\n\r\nselect\r\n\tname as 'Name',\r\n\tsum(total_destruction) / cast(sum(attacks_made) as float) as 'Destruction'\r\nfrom\r\n\t@attack_stats\r\ngroup by\r\n\tname,\r\n\ttag,\r\n\tclan,\r\n\tclan_tag\r\norder by\r\n\tsum(total_destruction) / cast(sum(attacks_made) as float) asc"
      }
     ]
    },
    {
     "title": "Stars",
     "type": "bargauge",
     "gridPos": { "h": 10, "w": 4, "x": 4, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "declare @latest_request_id int = (select top 1 id from requests order by timestamp desc)\r\ndeclare @latest_members table (tag nvarchar(16), name nvarchar(256))\r\ninsert into @latest_members\r\nselect\r\n\tm.tag,\r\n\tm.name\r\nfrom\r\n\trequests r\r\n\tjoin clans c on c.request_id = r.id\r\n\tjoin members m on m.clan_id = c.id\r\nwhere\r\n\tc.tag in ($clans)\r\n\tand m.tag in ($players)\r\n\tand r.id = @latest_request_id\r\n\t\r\ndeclare @attack_stats table (name nvarchar(256), tag nvarchar(16), clan nvarchar(256), clan_tag nvarchar(16), attacks_made int, total_stars int, total_destruction int, total_duration int, total_position int, total_enemy_position int, total_townhall int, total_enemy_townhall int)\r\nif '$warleagues' = 'Yes' begin\r\n\tdeclare @map_position table (clan_id int, member_id int, map_position int)\r\n\tinsert into @map_position\r\n\tselect\r\n\t\tlwc.id as clan_id,\r\n\t\tlwcm.id as member_id,\r\n\t\trow_number() over (partition by lwc.id order by lwcm.map_position) as map_position\r\n\tfrom\r\n\t\tleague_wars lw\r\n\t\tjoin league_war_details lwd on lwd.league_war_id = lw.id\r\n\t\tjoin league_war_clans lwc on lwc.league_war_id = lw.id\r\n\t\tjoin league_war_clan_members lwcm on lwcm.league_war_clan_id = lwc.id\r\n\twhere\r\n\t\t$__timeFilter(lwd.end_time)\r\n\r\n\tinsert into @attack_stats\r\n\tselect\r\n\t\tlwcm2.name as name,\r\n\t\tlwcm2.tag as tag,\r\n\t\tlwc2.name as clan,\r\n\t\tlwc2.tag as clan_tag,\r\n\t\tcount(lwcm.attack_attacker_tag) as attacks_made,\r\n\t\tsum(lwcm.attack_stars) as 'total_stars',\r\n\t\tsum(lwcm.attack_destruction_percentage) as 'total_destruction',\r\n\t\tsum(lwcm.attack_duration) as 'total_duration',\r\n\t\tsum(mp2.map_position) as 'total_position',\r\n\t\tsum(mp.map_position) as 'total_enemy_position',\r\n\t\tsum(lwcm2.town_hall_level) as 'total_townhall',\r\n\t\tsum(lwcm.town_hall_level) as 'total_enemy_townhall'\r\n\tfrom\r\n\t\tleague_wars lw\r\n\t\tjoin league_war_details lwd on lwd.league_war_id = lw.id\r\n\t\tjoin league_war_clans lwc on lwc.league_war_id = lw.id\r\n\t\tjoin league_war_clan_members lwcm on lwcm.league_war_clan_id = lwc.id\r\n\t\tjoin @map_position mp on mp.clan_id = lwc.id and mp.member_id = lwcm.id\r\n\t\tjoin league_war_clans lwc2 on lwc2.league_war_id = lw.id and lwc2.id <> lwc.id\r\n\t\tjoin league_war_clan_members lwcm2 on lwcm2.league_war_clan_id = lwc2.id and lwcm.attack_defender_tag = lwcm2.tag\r\n\t\tjoin @map_position mp2 on mp2.clan_id = lwc2.id and mp2.member_id = lwcm2.id\r\n\twhere\r\n\t\tlwc2.tag in ($clans)\r\n\t\tand (lwcm2.tag in (select tag from @latest_members) or '$onlycurrentmembers' = 'No' and lwcm2.tag in ($players))\r\n\tgroup by\r\n\t\tlwcm2.name,\r\n\t\tlwcm2.tag,\r\n\t\tlwc2.name,\r\n\t\tlwc2.tag\r\nend\r\nif '$normalwars' = 'Yes' begin\r\n\tinsert into @attack_stats\r\n\tselect\r\n\t\twcm2.name as name,\r\n\t\twcm2.tag as tag,\r\n\t\twc2.name as clan,\r\n\t\twc2.tag as clan_tag,\r\n\t\tcount(1) as attacks_made,\r\n\t\tsum(wa.stars) as 'total_stars',\r\n\t\tsum(wa.destruction_percentage) as 'total_destruction',\r\n\t\tsum(wa.duration) as 'total_duration',\r\n\t\tsum(wcm2.map_position) as 'total_position',\r\n\t\tsum(wcm.map_position) as 'total_enemy_position',\r\n\t\tsum(wcm2.town_hall_level) as 'total_townhall',\r\n\t\tsum(wcm.town_hall_level) as 'total_enemy_townhall'\r\n\tfrom\r\n\t\twars w\r\n\t\tjoin war_clans wc on wc.war_id = w.id\r\n\t\tjoin war_clan_members wcm on wcm.war_clan_id = wc.id\r\n\t\tjoin war_attacks wa on wa.war_clan_member_id = wcm.id\r\n\t\tjoin war_clans wc2 on wc2.war_id = w.id and wc2.id <> wc.id\r\n\t\tjoin war_clan_members wcm2 on wcm2.war_clan_id = wc2.id and wa.defender_tag = wcm2.tag\r\n\twhere\r\n\t\twc2.tag in ($clans)\r\n\t\tand (wcm2.tag in (select tag from @latest_members) or '$onlycurrentmembers' = 'No' and wcm2.tag in ($players))\r\n\t\tand $__timeFilter(w.end_time)\r\n\tgroup by\r\n\t\twcm2.name,\r\n\t\twcm2.tag,\r\n\t\twc2.name,\r\n\t\twc2.tag\r\nend\r\n\r\nselect\r\n\tname as 'Name',\r\n\tsum(total_stars) / cast(sum(attacks_made) as float) as 'Stars'\r\nfrom\r\n\t@attack_stats\r\ngroup by\r\n\tname,\r\n\ttag,\r\n\tclan,\r\n\tclan_tag\r\norder by\r\n\tsum(total_stars) / cast(sum(attacks_made) as float) asc"
      }
     ]
    },
    {
     "title": "Enemy Position",
     "type": "bargauge",
     "gridPos": { "h": 10, "w": 4, "x": 8, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "declare @latest_request_id int = (select top 1 id from requests order by timestamp desc)\r\ndeclare @latest_members table (tag nvarchar(16), name nvarchar(256))\r\ninsert into @latest_members\r\nselect\r\n\tm.tag,\r\n\tm.name\r\nfrom\r\n\trequests r\r\n\tjoin clans c on c.request_id = r.id\r\n\tjoin members m on m.clan_id = c.id\r\nwhere\r\n\tc.tag in ($clans)\r\n\tand m.tag in ($players)\r\n\tand r.id = @latest_request_id\r\n\t\r\ndeclare @attack_stats table (name nvarchar(256), tag nvarchar(16), clan nvarchar(256), clan_tag nvarchar(16), attacks_made int, total_stars int, total_destruction int, total_duration int, total_position int, total_enemy_position int, total_townhall int, total_enemy_townhall int)\r\nif '$warleagues' = 'Yes' begin\r\n\tdeclare @map_position table (clan_id int, member_id int, map_position int)\r\n\tinsert into @map_position\r\n\tselect\r\n\t\tlwc.id as clan_id,\r\n\t\tlwcm.id as member_id,\r\n\t\trow_number() over (partition by lwc.id order by lwcm.map_position) as map_position\r\n\tfrom\r\n\t\tleague_wars lw\r\n\t\tjoin league_war_details lwd on lwd.league_war_id = lw.id\r\n\t\tjoin league_war_clans lwc on lwc.league_war_id = lw.id\r\n\t\tjoin league_war_clan_members lwcm on lwcm.league_war_clan_id = lwc.id\r\n\twhere\r\n\t\t$__timeFilter(lwd.end_time)\r\n\r\n\tinsert into @attack_stats\r\n\tselect\r\n\t\tlwcm2.name as name,\r\n\t\tlwcm2.tag as tag,\r\n\t\tlwc2.name as clan,\r\n\t\tlwc2.tag as clan_tag,\r\n\t\tcount(lwcm.attack_attacker_tag) as attacks_made,\r\n\t\tsum(lwcm.attack_stars) as 'total_stars',\r\n\t\tsum(lwcm.attack_destruction_percentage) as 'total_destruction',\r\n\t\tsum(lwcm.attack_duration) as 'total_duration',\r\n\t\tsum(mp2.map_position) as 'total_position',\r\n\t\tsum(mp.map_position) as 'total_enemy_position',\r\n\t\tsum(lwcm2.town_hall_level) as 'total_townhall',\r\n\t\tsum(lwcm.town_hall_level) as 'total_enemy_townhall'\r\n\tfrom\r\n\t\tleague_wars lw\r\n\t\tjoin league_war_details lwd on lwd.league_war_id = lw.id\r\n\t\tjoin league_war_clans lwc on lwc.league_war_id = lw.id\r\n\t\tjoin league_war_clan_members lwcm on lwcm.league_war_clan_id = lwc.id\r\n\t\tjoin @map_position mp on mp.clan_id = lwc.id and mp.member_id = lwcm.id\r\n\t\tjoin league_war_clans lwc2 on lwc2.league_war_id = lw.id and lwc2.id <> lwc.id\r\n\t\tjoin league_war_clan_members lwcm2 on lwcm2.league_war_clan_id = lwc2.id and lwcm.attack_defender_tag = lwcm2.tag\r\n\t\tjoin @map_position mp2 on mp2.clan_id = lwc2.id and mp2.member_id = lwcm2.id\r\n\twhere\r\n\t\tlwc2.tag in ($clans)\r\n\t\tand (lwcm2.tag in (select tag from @latest_members) or '$onlycurrentmembers' = 'No' and lwcm2.tag in ($players))\r\n\tgroup by\r\n\t\tlwcm2.name,\r\n\t\tlwcm2.tag,\r\n\t\tlwc2.name,\r\n\t\tlwc2.tag\r\nend\r\nif '$normalwars' = 'Yes' begin\r\n\tinsert into @attack_stats\r\n\tselect\r\n\t\twcm2.name as name,\r\n\t\twcm2.tag as tag,\r\n\t\twc2.name as clan,\r\n\t\twc2.tag as clan_tag,\r\n\t\tcount(1) as attacks_made,\r\n\t\tsum(wa.stars) as 'total_stars',\r\n\t\tsum(wa.destruction_percentage) as 'total_destruction',\r\n\t\tsum(wa.duration) as 'total_duration',\r\n\t\tsum(wcm2.map_position) as 'total_position',\r\n\t\tsum(wcm.map_position) as 'total_enemy_position',\r\n\t\tsum(wcm2.town_hall_level) as 'total_townhall',\r\n\t\tsum(wcm.town_hall_level) as 'total_enemy_townhall'\r\n\tfrom\r\n\t\twars w\r\n\t\tjoin war_clans wc on wc.war_id = w.id\r\n\t\tjoin war_clan_members wcm on wcm.war_clan_id = wc.id\r\n\t\tjoin war_attacks wa on wa.war_clan_member_id = wcm.id\r\n\t\tjoin war_clans wc2 on wc2.war_id = w.id and wc2.id <> wc.id\r\n\t\tjoin war_clan_members wcm2 on wcm2.war_clan_id = wc2.id and wa.defender_tag = wcm2.tag\r\n\twhere\r\n\t\twc2.tag in ($clans)\r\n\t\tand (wcm2.tag in (select tag from @latest_members) or '$onlycurrentmembers' = 'No' and wcm2.tag in ($players))\r\n\t\tand $__timeFilter(w.end_time)\r\n\tgroup by\r\n\t\twcm2.name,\r\n\t\twcm2.tag,\r\n\t\twc2.name,\r\n\t\twc2.tag\r\nend\r\n\r\nselect\r\n\tname as 'Name',\r\n\tsum(total_enemy_position) / cast(sum(attacks_made) as float) as 'Enemy Position'\r\nfrom\r\n\t@attack_stats\r\ngroup by\r\n\tname,\r\n\ttag,\r\n\tclan,\r\n\tclan_tag\r\norder by\r\n\tsum(total_enemy_position) / cast(sum(attacks_made) as float) asc"
      }
     ]
    },
    {
     "title": "Position Diff",
     "type": "bargauge",
     "gridPos": { "h": 10, "w": 4, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "declare @latest_request_id int = (select top 1 id from requests order by timestamp desc)\r\ndeclare @latest_members table (tag nvarchar(16), name nvarchar(256))\r\ninsert into @latest_members\r\nselect\r\n\tm.tag,\r\n\tm.name\r\nfrom\r\n\trequests r\r\n\tjoin clans c on c.request_id = r.id\r\n\tjoin members m on m.clan_id = c.id\r\nwhere\r\n\tc.tag in ($clans)\r\n\tand m.tag in ($players)\r\n\tand r.id = @latest_request_id\r\n\t\r\ndeclare @attack_stats table (name nvarchar(256), tag nvarchar(16), clan nvarchar(256), clan_tag nvarchar(16), attacks_made int, total_stars int, total_destruction int, total_duration int, total_position int, total_enemy_position int, total_townhall int, total_enemy_townhall int)\r\nif '$warleagues' = 'Yes' begin\r\n\tdeclare @map_position table (clan_id int, member_id int, map_position int)\r\n\tinsert into @map_position\r\n\tselect\r\n\t\tlwc.id as clan_id,\r\n\t\tlwcm.id as member_id,\r\n\t\trow_number() over (partition by lwc.id order by lwcm.map_position) as map_position\r\n\tfrom\r\n\t\tleague_wars lw\r\n\t\tjoin league_war_details lwd on lwd.league_war_id = lw.id\r\n\t\tjoin league_war_clans lwc on lwc.league_war_id = lw.id\r\n\t\tjoin league_war_clan_members lwcm on lwcm.league_war_clan_id = lwc.id\r\n\twhere\r\n\t\t$__timeFilter(lwd.end_time)\r\n\r\n\tinsert into @attack_stats\r\n\tselect\r\n\t\tlwcm2.name as name,\r\n\t\tlwcm2.tag as tag,\r\n\t\tlwc2.name as clan,\r\n\t\tlwc2.tag as clan_tag,\r\n\t\tcount(lwcm.attack_attacker_tag) as attacks_made,\r\n\t\tsum(lwcm.attack_stars) as 'total_stars',\r\n\t\tsum(lwcm.attack_destruction_percentage) as 'total_destruction',\r\n\t\tsum(lwcm.attack_duration) as 'total_duration',\r\n\t\tsum(mp2.map_position) as 'total_position',\r\n\t\tsum(mp.map_position) as 'total_enemy_position',\r\n\t\tsum(lwcm2.town_hall_level) as 'total_townhall',\r\n\t\tsum(lwcm.town_hall_level) as 'total_enemy_townhall'\r\n\tfrom\r\n\t\tleague_wars lw\r\n\t\tjoin league_war_details lwd on lwd.league_war_id = lw.id\r\n\t\tjoin league_war_clans lwc on lwc.league_war_id = lw.id\r\n\t\tjoin league_war_clan_members lwcm on lwcm.league_war_clan_id = lwc.id\r\n\t\tjoin @map_position mp on mp.clan_id = lwc.id and mp.member_id = lwcm.id\r\n\t\tjoin league_war_clans lwc2 on lwc2.league_war_id = lw.id and lwc2.id <> lwc.id\r\n\t\tjoin league_war_clan_members lwcm2 on lwcm2.league_war_clan_id = lwc2.id and lwcm.attack_defender_tag = lwcm2.tag\r\n\t\tjoin @map_position mp2 on mp2.clan_id = lwc2.id and mp2.member_id = lwcm2.id\r\n\twhere\r\n\t\tlwc2.tag in ($clans)\r\n\t\tand (lwcm2.tag in (select tag from @latest_members) or '$onlycurrentmembers' = 'No' and lwcm2.tag in ($players))\r\n\tgroup by\r\n\t\tlwcm2.name,\r\n\t\tlwcm2.tag,\r\n\t\tlwc2.name,\r\n\t\tlwc2.tag\r\nend\r\nif '$normalwars' = 'Yes' begin\r\n\tinsert into @attack_stats\r\n\tselect\r\n\t\twcm2.name as name,\r\n\t\twcm2.tag as tag,\r\n\t\twc2.name as clan,\r\n\t\twc2.tag as clan_tag,\r\n\t\tcount(1) as attacks_made,\r\n\t\tsum(wa.stars) as 'total_stars',\r\n\t\tsum(wa.destruction_percentage) as 'total_destruction',\r\n\t\tsum(wa.duration) as 'total_duration',\r\n\t\tsum(wcm2.map_position) as 'total_position',\r\n\t\tsum(wcm.map_position) as 'total_enemy_position',\r\n\t\tsum(wcm2.town_hall_level) as 'total_townhall',\r\n\t\tsum(wcm.town_hall_level) as 'total_enemy_townhall'\r\n\tfrom\r\n\t\twars w\r\n\t\tjoin war_clans wc on wc.war_id = w.id\r\n\t\tjoin war_clan_members wcm on wcm.war_clan_id = wc.id\r\n\t\tjoin war_attacks wa on wa.war_clan_member_id = wcm.id\r\n\t\tjoin war_clans wc2 on wc2.war_id = w.id and wc2.id <> wc.id\r\n\t\tjoin war_clan_members wcm2 on wcm2.war_clan_id = wc2.id and wa.defender_tag = wcm2.tag\r\n\twhere\r\n\t\twc2.tag in ($clans)\r\n\t\tand (wcm2.tag in (select tag from @latest_members) or '$onlycurrentmembers' = 'No' and wcm2.tag in ($players))\r\n\t\tand $__timeFilter(w.end_time)\r\n\tgroup by\r\n\t\twcm2.name,\r\n\t\twcm2.tag,\r\n\t\twc2.name,\r\n\t\twc2.tag\r\nend\r\n\r\nselect\r\n\tname as 'Name',\r\n\t(sum(total_enemy_position) - sum(total_position)) / cast(sum(attacks_made) as float) as 'Position Diff'\r\nfrom\r\n\t@attack_stats\r\ngroup by\r\n\tname,\r\n\ttag,\r\n\tclan,\r\n\tclan_tag\r\norder by\r\n\t(sum(total_enemy_position) - sum(total_position)) / cast(sum(attacks_made) as float) asc"
      }
     ]
    },
    {
     "title": "Enemy Townhall",
     "type": "bargauge",
     "gridPos": { "h": 10, "w": 4, "x": 16, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "declare @latest_request_id int = (select top 1 id from requests order by timestamp desc)\r\ndeclare @latest_members table (tag nvarchar(16), name nvarchar(256))\r\ninsert into @latest_members\r\nselect\r\n\tm.tag,\r\n\tm.name\r\nfrom\r\n\trequests r\r\n\tjoin clans c on c.request_id = r.id\r\n\tjoin members m on m.clan_id = c.id\r\nwhere\r\n\tc.tag in ($clans)\r\n\tand m.tag in ($players)\r\n\tand r.id = @latest_request_id\r\n\t\r\ndeclare @attack_stats table (name nvarchar(256), tag nvarchar(16), clan nvarchar(256), clan_tag nvarchar(16), attacks_made int, total_stars int, total_destruction int, total_duration int, total_position int, total_enemy_position int, total_townhall int, total_enemy_townhall int)\r\nif '$warleagues' = 'Yes' begin\r\n\tdeclare @map_position table (clan_id int, member_id int, map_position int)\r\n\tinsert into @map_position\r\n\tselect\r\n\t\tlwc.id as clan_id,\r\n\t\tlwcm.id as member_id,\r\n\t\trow_number() over (partition by lwc.id order by lwcm.map_position) as map_position\r\n\tfrom\r\n\t\tleague_wars lw\r\n\t\tjoin league_war_details lwd on lwd.league_war_id = lw.id\r\n\t\tjoin league_war_clans lwc on lwc.league_war_id = lw.id\r\n\t\tjoin league_war_clan_members lwcm on lwcm.league_war_clan_id = lwc.id\r\n\twhere\r\n\t\t$__timeFilter(lwd.end_time)\r\n\r\n\tinsert into @attack_stats\r\n\tselect\r\n\t\tlwcm2.name as name,\r\n\t\tlwcm2.tag as tag,\r\n\t\tlwc2.name as clan,\r\n\t\tlwc2.tag as clan_tag,\r\n\t\tcount(lwcm.attack_attacker_tag) as attacks_made,\r\n\t\tsum(lwcm.attack_stars) as 'total_stars',\r\n\t\tsum(lwcm.attack_destruction_percentage) as 'total_destruction',\r\n\t\tsum(lwcm.attack_duration) as 'total_duration',\r\n\t\tsum(mp2.map_position) as 'total_position',\r\n\t\tsum(mp.map_position) as 'total_enemy_position',\r\n\t\tsum(lwcm2.town_hall_level) as 'total_townhall',\r\n\t\tsum(lwcm.town_hall_level) as 'total_enemy_townhall'\r\n\tfrom\r\n\t\tleague_wars lw\r\n\t\tjoin league_war_details lwd on lwd.league_war_id = lw.id\r\n\t\tjoin league_war_clans lwc on lwc.league_war_id = lw.id\r\n\t\tjoin league_war_clan_members lwcm on lwcm.league_war_clan_id = lwc.id\r\n\t\tjoin @map_position mp on mp.clan_id = lwc.id and mp.member_id = lwcm.id\r\n\t\tjoin league_war_clans lwc2 on lwc2.league_war_id = lw.id and lwc2.id <> lwc.id\r\n\t\tjoin league_war_clan_members lwcm2 on lwcm2.league_war_clan_id = lwc2.id and lwcm.attack_defender_tag = lwcm2.tag\r\n\t\tjoin @map_position mp2 on mp2.clan_id = lwc2.id and mp2.member_id = lwcm2.id\r\n\twhere\r\n\t\tlwc2.tag in ($clans)\r\n\t\tand (lwcm2.tag in (select tag from @latest_members) or '$onlycurrentmembers' = 'No' and lwcm2.tag in ($players))\r\n\tgroup by\r\n\t\tlwcm2.name,\r\n\t\tlwcm2.tag,\r\n\t\tlwc2.name,\r\n\t\tlwc2.tag\r\nend\r\nif '$normalwars' = 'Yes' begin\r\n\tinsert into @attack_stats\r\n\tselect\r\n\t\twcm2.name as name,\r\n\t\twcm2.tag as tag,\r\n\t\twc2.name as clan,\r\n\t\twc2.tag as clan_tag,\r\n\t\tcount(1) as attacks_made,\r\n\t\tsum(wa.stars) as 'total_stars',\r\n\t\tsum(wa.destruction_percentage) as 'total_destruction',\r\n\t\tsum(wa.duration) as 'total_duration',\r\n\t\tsum(wcm2.map_position) as 'total_position',\r\n\t\tsum(wcm.map_position) as 'total_enemy_position',\r\n\t\tsum(wcm2.town_hall_level) as 'total_townhall',\r\n\t\tsum(wcm.town_hall_level) as 'total_enemy_townhall'\r\n\tfrom\r\n\t\twars w\r\n\t\tjoin war_clans wc on wc.war_id = w.id\r\n\t\tjoin war_clan_members wcm on wcm.war_clan_id = wc.id\r\n\t\tjoin war_attacks wa on wa.war_clan_member_id = wcm.id\r\n\t\tjoin war_clans wc2 on wc2.war_id = w.id and wc2.id <> wc.id\r\n\t\tjoin war_clan_members wcm2 on wcm2.war_clan_id = wc2.id and wa.defender_tag = wcm2.tag\r\n\twhere\r\n\t\twc2.tag in ($clans)\r\n\t\tand (wcm2.tag in (select tag from @latest_members) or '$onlycurrentmembers' = 'No' and wcm2.tag in ($players))\r\n\t\tand $__timeFilter(w.end_time)\r\n\tgroup by\r\n\t\twcm2.name,\r\n\t\twcm2.tag,\r\n\t\twc2.name,\r\n\t\twc2.tag\r\nend\r\n\r\nselect\r\n\tname as 'Name',\r\n\tsum(total_enemy_townhall) / cast(sum(attacks_made) as float) as 'Enemy Townhall'\r\nfrom\r\n\t@attack_stats\r\ngroup by\r\n\tname,\r\n\ttag,\r\n\tclan,\r\n\tclan_tag\r\norder by\r\n\tsum(total_enemy_townhall) / cast(sum(attacks_made) as float) desc"
      }
     ]
    },
    {
     "title": "Townhall diff",
     "type": "bargauge",
     "gridPos": { "h": 10, "w": 4, "x": 20, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "declare @latest_request_id int = (select top 1 id from requests order by timestamp desc)\r\ndeclare @latest_members table (tag nvarchar(16), name nvarchar(256))\r\ninsert into @latest_members\r\nselect\r\n\tm.tag,\r\n\tm.name\r\nfrom\r\n\trequests r\r\n\tjoin clans c on c.request_id = r.id\r\n\tjoin members m on m.clan_id = c.id\r\nwhere\r\n\tc.tag in ($clans)\r\n\tand m.tag in ($players)\r\n\tand r.id = @latest_request_id\r\n\t\r\ndeclare @attack_stats table (name nvarchar(256), tag nvarchar(16), clan nvarchar(256), clan_tag nvarchar(16), attacks_made int, total_stars int, total_destruction int, total_duration int, total_position int, total_enemy_position int, total_townhall int, total_enemy_townhall int)\r\nif '$warleagues' = 'Yes' begin\r\n\tdeclare @map_position table (clan_id int, member_id int, map_position int)\r\n\tinsert into @map_position\r\n\tselect\r\n\t\tlwc.id as clan_id,\r\n\t\tlwcm.id as member_id,\r\n\t\trow_number() over (partition by lwc.id order by lwcm.map_position) as map_position\r\n\tfrom\r\n\t\tleague_wars lw\r\n\t\tjoin league_war_details lwd on lwd.league_war_id = lw.id\r\n\t\tjoin league_war_clans lwc on lwc.league_war_id = lw.id\r\n\t\tjoin league_war_clan_members lwcm on lwcm.league_war_clan_id = lwc.id\r\n\twhere\r\n\t\t$__timeFilter(lwd.end_time)\r\n\r\n\tinsert into @attack_stats\r\n\tselect\r\n\t\tlwcm2.name as name,\r\n\t\tlwcm2.tag as tag,\r\n\t\tlwc2.name as clan,\r\n\t\tlwc2.tag as clan_tag,\r\n\t\tcount(lwcm.attack_attacker_tag) as attacks_made,\r\n\t\tsum(lwcm.attack_stars) as 'total_stars',\r\n\t\tsum(lwcm.attack_destruction_percentage) as 'total_destruction',\r\n\t\tsum(lwcm.attack_duration) as 'total_duration',\r\n\t\tsum(mp2.map_position) as 'total_position',\r\n\t\tsum(mp.map_position) as 'total_enemy_position',\r\n\t\tsum(lwcm2.town_hall_level) as 'total_townhall',\r\n\t\tsum(lwcm.town_hall_level) as 'total_enemy_townhall'\r\n\tfrom\r\n\t\tleague_wars lw\r\n\t\tjoin league_war_details lwd on lwd.league_war_id = lw.id\r\n\t\tjoin league_war_clans lwc on lwc.league_war_id = lw.id\r\n\t\tjoin league_war_clan_members lwcm on lwcm.league_war_clan_id = lwc.id\r\n\t\tjoin @map_position mp on mp.clan_id = lwc.id and mp.member_id = lwcm.id\r\n\t\tjoin league_war_clans lwc2 on lwc2.league_war_id = lw.id and lwc2.id <> lwc.id\r\n\t\tjoin league_war_clan_members lwcm2 on lwcm2.league_war_clan_id = lwc2.id and lwcm.attack_defender_tag = lwcm2.tag\r\n\t\tjoin @map_position mp2 on mp2.clan_id = lwc2.id and mp2.member_id = lwcm2.id\r\n\twhere\r\n\t\tlwc2.tag in ($clans)\r\n\t\tand (lwcm2.tag in (select tag from @latest_members) or '$onlycurrentmembers' = 'No' and lwcm2.tag in ($players))\r\n\tgroup by\r\n\t\tlwcm2.name,\r\n\t\tlwcm2.tag,\r\n\t\tlwc2.name,\r\n\t\tlwc2.tag\r\nend\r\nif '$normalwars' = 'Yes' begin\r\n\tinsert into @attack_stats\r\n\tselect\r\n\t\twcm2.name as name,\r\n\t\twcm2.tag as tag,\r\n\t\twc2.name as clan,\r\n\t\twc2.tag as clan_tag,\r\n\t\tcount(1) as attacks_made,\r\n\t\tsum(wa.stars) as 'total_stars',\r\n\t\tsum(wa.destruction_percentage) as 'total_destruction',\r\n\t\tsum(wa.duration) as 'total_duration',\r\n\t\tsum(wcm2.map_position) as 'total_position',\r\n\t\tsum(wcm.map_position) as 'total_enemy_position',\r\n\t\tsum(wcm2.town_hall_level) as 'total_townhall',\r\n\t\tsum(wcm.town_hall_level) as 'total_enemy_townhall'\r\n\tfrom\r\n\t\twars w\r\n\t\tjoin war_clans wc on wc.war_id = w.id\r\n\t\tjoin war_clan_members wcm on wcm.war_clan_id = wc.id\r\n\t\tjoin war_attacks wa on wa.war_clan_member_id = wcm.id\r\n\t\tjoin war_clans wc2 on wc2.war_id = w.id and wc2.id <> wc.id\r\n\t\tjoin war_clan_members wcm2 on wcm2.war_clan_id = wc2.id and wa.defender_tag = wcm2.tag\r\n\twhere\r\n\t\twc2.tag in ($clans)\r\n\t\tand (wcm2.tag in (select tag from @latest_members) or '$onlycurrentmembers' = 'No' and wcm2.tag in ($players))\r\n\t\tand $__timeFilter(w.end_time)\r\n\tgroup by\r\n\t\twcm2.name,\r\n\t\twcm2.tag,\r\n\t\twc2.name,\r\n\t\twc2.tag\r\nend\r\n\r\nselect\r\n\tname as 'Name',\r\n\t(sum(total_enemy_townhall) - sum(total_townhall)) / cast(sum(attacks_made) as float) as 'Townhall Diff'\r\nfrom\r\n\t@attack_stats\r\ngroup by\r\n\tname,\r\n\ttag,\r\n\tclan,\r\n\tclan_tag\r\norder by\r\n\t(sum(total_enemy_townhall) - sum(total_townhall)) / cast(sum(attacks_made) as float) desc"
      }
     ]
    }
   ]
  },
  {
   "title": "Clan",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Table",
     "type": "table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "rawSql": "declare @latest_request_id int = (select top 1 id from requests order by timestamp desc)\r\ndeclare @latest_members table (tag nvarchar(16), name nvarchar(256))\r\ninsert into @latest_members\r\nselect\r\n\tm.tag,\r\n\tm.name\r\nfrom\r\n\trequests r\r\n\tjoin clans c on c.request_id = r.id\r\n\tjoin members m on m.clan_id = c.id\r\nwhere\r\n\tc.tag in ($clans)\r\n\tand m.tag in ($players)\r\n\tand r.id = @latest_request_id\r\n\r\ndeclare @join_date table (tag nvarchar(16), join_date datetime)\r\ninsert into @join_date\r\nselect\r\n\tlm.tag,\r\n\tmin(r.timestamp)\r\nfrom\r\n\t@latest_members lm\r\n\tjoin members m on m.tag = lm.tag\r\n\tjoin clans c on c.id = m.clan_id\r\n\tjoin requests r on r.id = c.request_id\r\ngroup by\r\n\tlm.tag\r\n\r\ndeclare @attack_stats table (tag nvarchar(16), attacks_made int, attacks_available int)\r\nif '$warleagues' = 'Yes' begin\r\n\tinsert into @attack_stats\r\n\tselect\r\n\t\tlm.tag as tag,\r\n\t\tsum(case when $__timeFilter(lwd.end_time) and lwcm.attack_attacker_tag is not null then 1 else 0 end) as attacks_made,\r\n\t\tsum(case when $__timeFilter(lwd.end_time) then 1 else 0 end) as attacks_available\r\n\tfrom\r\n\t\t@latest_members lm\r\n\t\tleft join league_war_clan_members lwcm on lwcm.tag = lm.tag\r\n\t\tleft join league_war_clans lwc on lwc.id = lwcm.league_war_clan_id\r\n\t\tleft join league_wars lw on lw.id = lwc.league_war_id\r\n\t\tleft join league_war_details lwd on lwd.league_war_id = lw.id\r\n\tgroup by\r\n\t\tlm.tag\r\nend\r\n\r\nif '$normalwars' = 'Yes' begin\r\n\tdeclare @attacks_available table (tag nvarchar(16), attacks_available int)\r\n\tinsert into @attacks_available\r\n\tselect\r\n\t\tlm.tag,\r\n\t\tsum(case when $__timeFilter(w.end_time) then w.attacks_per_member else 0 end) attacks_available\r\n\tfrom\r\n\t\t@latest_members lm\r\n\t\tleft join war_clan_members wcm on wcm.tag = lm.tag\r\n\t\tleft join war_clans wc on wc.id = wcm.war_clan_id\r\n\t\tleft join wars w on w.id = wc.war_id\r\n\tgroup by\r\n\t\tlm.tag\r\n\r\n\tinsert into @attack_stats\r\n\tselect\r\n\t\tlm.tag as tag,\r\n\t\tsum(case when $__timeFilter(w.end_time) and wa.id is not null then 1 else 0 end) as attacks_made,\r\n\t\taa.attacks_available as attacks_available\r\n\tfrom\r\n\t\t@latest_members lm\r\n\t\tjoin @attacks_available aa on aa.tag = lm.tag\r\n\t\tleft join war_clan_members wcm on wcm.tag = lm.tag\r\n\t\tleft join war_attacks wa on wa.war_clan_member_id = wcm.id\r\n\t\tleft join war_clans wc on wc.id = wcm.war_clan_id\r\n\t\tleft join wars w on w.id = wc.war_id\r\n\tgroup by\r\n\t\tlm.tag,\r\n\t\taa.attacks_available\r\nend\r\n\r\ndeclare @attack_stats_grouped table (tag nvarchar(16), attacks_made int, attacks_available int)\r\ninsert into @attack_stats_grouped\r\nselect\r\n\ttag,\r\n\tsum(attacks_made),\r\n\tsum(attacks_available)\r\nfrom\r\n\t@attack_stats\r\ngroup by\r\n\ttag\r\n\r\nselect\r\n\trow_number() over(\r\n\t\torder by case when asg.attacks_available > 0 then asg.attacks_made / cast(asg.attacks_available as float) else 0 end desc,\r\n\t\tasg.attacks_available asc,\r\n\t\tjd.join_date desc\r\n\t) as 'Number',\r\n\tlm.name as 'Name',\r\n\tjd.join_date as 'Joined',\r\n\tcase when asg.attacks_available > 0 then asg.attacks_made / cast(asg.attacks_available as float) else null end as 'Attack Utilization',\r\n\tasg.attacks_made as 'Attacks Made',\r\n\tasg.attacks_available as 'Attacks Available'\r\nfrom\r\n\t@latest_members lm\r\n\tjoin @join_date jd on jd.tag = lm.tag\r\n\tjoin @attack_stats_grouped asg on asg.tag = lm.tag\r\norder by\r\n\tcase when asg.attacks_available > 0 then asg.attacks_made / cast(asg.attacks_available as float) else 0 end desc,\r\n\tasg.attacks_available asc,\r\n\tjd.join_date desc"
      }
     ]
    },
    {
     "title": "Members",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 16 },
     "targets": [
      {
       "rawSql": "select\n\tr.timestamp as time,\n\tc.members as 'Members'\nfrom\n\trequests r\n\tjoin clans c on c.request_id = r.id\nwhere\n\t$__timeFilter(r.timestamp)\norder by\n\tr.timestamp"
      }
     ]
    },
    {
     "title": "Attacks Made",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 16 },
     "targets": [
      {
       "rawSql": "declare @latest_request_id int = (select top 1 id from requests order by timestamp desc)\r\ndeclare @latest_members table (tag nvarchar(16), name nvarchar(256))\r\ninsert into @latest_members\r\nselect\r\n\tm.tag,\r\n\tm.name\r\nfrom\r\n\trequests r\r\n\tjoin clans c on c.request_id = r.id\r\n\tjoin members m on m.clan_id = c.id\r\nwhere\r\n\tc.tag in ($clans)\r\n\tand m.tag in ($players)\r\n\r\nselect\r\n\tlwd.end_time as time,\r\n\tcount(lwcm.attack_attacker_tag) as 'Attacks Made'\r\nfrom\r\n\tleague_wars lw\r\n\tjoin league_war_details lwd on lwd.league_war_id = lw.id\r\n\tjoin league_war_clans lwc on lwc.league_war_id = lw.id\r\n\tjoin league_war_clan_members lwcm on lwcm.league_war_clan_id = lwc.id\r\nwhere\r\n\tlwc.tag in ($clans)\r\n\tand (lwcm.tag in (select tag from @latest_members) or '$onlycurrentmembers' = 'No' and lwcm.tag in ($players))\r\n\tand $__timeFilter(lwd.end_time)\r\n\tand lwc.tag in (select distinct tag from clans)\r\n\tand '$warleagues' = 'Yes'\r\ngroup by\r\n\tlwd.end_time\r\nunion\r\nselect\r\n\tw.end_time as time,\r\n\tcount(1) as 'Attacks Made'\r\nfrom\r\n\twars w\r\n\tjoin war_clans wc on wc.war_id = w.id\r\n\tjoin war_clan_members wcm on wcm.war_clan_id = wc.id\r\n\tjoin war_attacks wa on wa.war_clan_member_id = wcm.id\r\nwhere\r\n\twc.tag in ($clans)\r\n\tand (wcm.tag in (select tag from @latest_members) or '$onlycurrentmembers' = 'No' and wcm.tag in ($players))\r\n\tand $__timeFilter(w.end_time)\r\n\tand wc.tag in (select distinct tag from clans)\r\n\tand '$normalwars' = 'Yes'\r\ngroup by\r\n\tw.end_time\r\norder by\r\n\tend_time"
      }
     ]
    },
    {
     "title": "Stars",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 16 },
     "targets": [
      {
       "rawSql": "declare @latest_request_id int = (select top 1 id from requests order by timestamp desc)\r\ndeclare @latest_members table (tag nvarchar(16), name nvarchar(256))\r\ninsert into @latest_members\r\nselect\r\n\tm.tag,\r\n\tm.name\r\nfrom\r\n\trequests r\r\n\tjoin clans c on c.request_id = r.id\r\n\tjoin members m on m.clan_id = c.id\r\nwhere\r\n\tc.tag in ($clans)\r\n\tand m.tag in ($players)\r\n\tand r.id = @latest_request_id\r\n\r\nselect\r\n\tlwd.end_time as time,\r\n\tsum(lwcm.attack_stars) as 'Stars'\r\nfrom\r\n\tleague_wars lw\r\n\tjoin league_war_details lwd on lwd.league_war_id = lw.id\r\n\tjoin league_war_clans lwc on lwc.league_war_id = lw.id\r\n\tjoin league_war_clan_members lwcm on lwcm.league_war_clan_id = lwc.id\r\nwhere\r\n\tlwc.tag in ($clans)\r\n\tand (lwcm.tag in (select tag from @latest_members) or '$onlycurrentmembers' = 'No' and lwcm.tag in ($players))\r\n\tand $__timeFilter(lwd.end_time)\r\n\tand lwc.tag in (select distinct tag from clans)\r\n\tand '$warleagues' = 'Yes'\r\ngroup by\r\n\tlwd.end_time\r\nunion\r\nselect\r\n\tw.end_time as time,\r\n\tsum(wa.stars) as 'Stars'\r\nfrom\r\n\twars w\r\n\tjoin war_clans wc on wc.war_id = w.id\r\n\tjoin war_clan_members wcm on wcm.war_clan_id = wc.id\r\n\tjoin war_attacks wa on wa.war_clan_member_id = wcm.id\r\nwhere\r\n\twc.tag in ($clans)\r\n\tand (wcm.tag in (select tag from @latest_members) or '$onlycurrentmembers' = 'No' and wcm.tag in ($players))\r\n\tand $__timeFilter(w.end_time)\r\n\tand wc.tag in (select distinct tag from clans)\r\n\tand '$normalwars' = 'Yes'\r\ngroup by\r\n\tw.end_time\r\norder by\r\n\tend_time"
      }
     ]
    }
   ]
  },
  {
   "title": "Clan Members",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Table",
     "type": "table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "rawSql": "declare @record_id int\nselect top 1 @record_id = id from requests order by timestamp desc\nselect\n\tm.name as 'Name',\n\tm.trophies as 'Trophies',\n\tm.versus_trophies as 'Versus Trophies',\n\tm.donations as 'Donations',\n\tm.donations_received as 'Donations Received'\nfrom\n\trequests r\n\tjoin clans c on c.request_id = r.id\n\tjoin members m on m.clan_id = c.id\nwhere\n\tm.tag in ($players)\n\tand $__timeFilter(r.timestamp)\n\tand r.id = @record_id\norder by\n\tm.donations desc,\n\tm.donations_received desc,\n\tm.trophies desc"
      }
     ]
    },
    {
     "title": "Donations",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "rawSql": "declare @latest_request_id int = (select top 1 id from requests order by timestamp desc)\r\ndeclare @latest_members table (tag nvarchar(16), name nvarchar(256))\r\ninsert into @latest_members\r\nselect\r\n\tm.tag,\r\n\tm.name\r\nfrom\r\n\trequests r\r\n\tjoin clans c on c.request_id = r.id\r\n\tjoin members m on m.clan_id = c.id\r\nwhere\r\n\tc.tag in ($clans)\r\n\tand m.tag in ($players)\r\n\tand r.id = @latest_request_id\r\n\t\r\nselect\r\n\tr.timestamp as time,\r\n\tm.name as 'Name',\r\n\tmax(m.donations)\r\nfrom\r\n\trequests r\r\n\tjoin clans c on c.request_id = r.id\r\n\tjoin members m on m.clan_id = c.id\r\nwhere\r\n\t(m.tag in (select tag from @latest_members) or '$onlycurrentmembers' = 'No' and m.tag in ($players))\r\n\tand m.donations > 0\r\n\tand $__timeFilter(r.timestamp)\r\ngroup by\r\n\tr.timestamp,\r\n\tm.name,\r\n\tm.tag\r\norder by\r\n\tr.timestamp"
      }
     ]
    },
    {
     "title": "Donations Received",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "rawSql": "declare @latest_request_id int = (select top 1 id from requests order by timestamp desc)\r\ndeclare @latest_members table (tag nvarchar(16), name nvarchar(256))\r\ninsert into @latest_members\r\nselect\r\n\tm.tag,\r\n\tm.name\r\nfrom\r\n\trequests r\r\n\tjoin clans c on c.request_id = r.id\r\n\tjoin members m on m.clan_id = c.id\r\nwhere\r\n\tc.tag in ($clans)\r\n\tand m.tag in ($players)\r\n\tand r.id = @latest_request_id\r\n\t\r\nselect\r\n\tr.timestamp as time,\r\n\tm.name as 'Name',\r\n\tmax(m.donations_received)\r\nfrom\r\n\trequests r\r\n\tjoin clans c on c.request_id = r.id\r\n\tjoin members m on m.clan_id = c.id\r\nwhere\r\n\t(m.tag in (select tag from @latest_members) or '$onlycurrentmembers' = 'No' and m.tag in ($players))\r\n\tand m.donations_received > 0\r\n\tand $__timeFilter(r.timestamp)\r\ngroup by\r\n\tr.timestamp,\r\n\tm.name,\r\n\tm.tag\r\norder by\r\n\tr.timestamp"
      }
     ]
    },
    {
     "title": "Trophies",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "rawSql": "declare @latest_request_id int = (select top 1 id from requests order by timestamp desc)\r\ndeclare @latest_members table (tag nvarchar(16), name nvarchar(256))\r\ninsert into @latest_members\r\nselect\r\n\tm.tag,\r\n\tm.name\r\nfrom\r\n\trequests r\r\n\tjoin clans c on c.request_id = r.id\r\n\tjoin members m on m.clan_id = c.id\r\nwhere\r\n\tc.tag in ($clans)\r\n\tand m.tag in ($players)\r\n\tand r.id = @latest_request_id\r\n\t\r\nselect\r\n\tr.timestamp as time,\r\n\tm.name as 'Name',\r\n\tmax(m.trophies)\r\nfrom\r\n\trequests r\r\n\tjoin clans c on c.request_id = r.id\r\n\tjoin members m on m.clan_id = c.id\r\nwhere\r\n\t(m.tag in (select tag from @latest_members) or '$onlycurrentmembers' = 'No' and m.tag in ($players))\r\n\tand $__timeFilter(r.timestamp)\r\ngroup by\r\n\tr.timestamp,\r\n\tm.name,\r\n\tm.tag\r\norder by\r\n\tr.timestamp"
      }
     ]
    },
    {
     "title": "Versus Trophies",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "rawSql": "declare @latest_request_id int = (select top 1 id from requests order by timestamp desc)\r\ndeclare @latest_members table (tag nvarchar(16), name nvarchar(256))\r\ninsert into @latest_members\r\nselect\r\n\tm.tag,\r\n\tm.name\r\nfrom\r\n\trequests r\r\n\tjoin clans c on c.request_id = r.id\r\n\tjoin members m on m.clan_id = c.id\r\nwhere\r\n\tc.tag in ($clans)\r\n\tand m.tag in ($players)\r\n\tand r.id = @latest_request_id\r\n\t\r\nselect\r\n\tr.timestamp as time,\r\n\tm.name as 'Name',\r\n\tmax(m.versus_trophies)\r\nfrom\r\n\trequests r\r\n\tjoin clans c on c.request_id = r.id\r\n\tjoin members m on m.clan_id = c.id\r\nwhere\r\n\t(m.tag in (select tag from @latest_members) or '$onlycurrentmembers' = 'No' and m.tag in ($players))\r\n\tand $__timeFilter(r.timestamp)\r\ngroup by\r\n\tr.timestamp,\r\n\tm.name,\r\n\tm.tag\r\norder by\r\n\tr.timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Attacks by Townhall",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Count",
     "type": "table",
     "gridPos": { "h": 15, "w": 12, "x": 0, "y": 7 },
     "targets": [
      {
       "rawSql": "declare @latest_request_id int = (select top 1 id from requests order by timestamp desc)\r\ndeclare @latest_members table (tag nvarchar(16), name nvarchar(256))\r\ninsert into @latest_members\r\nselect\r\n\tm.tag,\r\n\tm.name\r\nfrom\r\n\trequests r\r\n\tjoin clans c on c.request_id = r.id\r\n\tjoin members m on m.clan_id = c.id\r\nwhere\r\n\tc.tag in ($clans)\r\n\tand m.tag in ($players)\r\n\tand r.id = @latest_request_id\r\n\t\r\ndeclare @ints table (ints int)\r\ninsert into @ints (ints) values (1), (2), (3), (4), (5), (6), (7), (8), (9), (10), (11), (12), (13), (14)\r\n\r\ndeclare @values table (\r\n\tints int,\r\n\tv1 int, v2 int, v3 int, v4 int, v5 int, v6 int, v7 int, v8 int, v9 int, v10 int, v11 int, v12 int, v13 int, v14 int,\r\n\tc1 int, c2 int, c3 int, c4 int, c5 int, c6 int, c7 int, c8 int, c9 int, c10 int, c11 int, c12 int, c13 int, c14 int\r\n)\r\n\r\nif '$warleagues' = 'Yes' begin\r\n\tinsert into @values\r\n\tselect\r\n\t\tints as 'Defender',\r\n\t\tsum(case when lwcm.town_hall_level = 1 then  1 end) as 'v1',\r\n\t\tsum(case when lwcm.town_hall_level = 2 then  1 end) as 'v2',\r\n\t\tsum(case when lwcm.town_hall_level = 3 then  1 end) as 'v3',\r\n\t\tsum(case when lwcm.town_hall_level = 4 then  1 end) as 'v4',\r\n\t\tsum(case when lwcm.town_hall_level = 5 then  1 end) as 'v5',\r\n\t\tsum(case when lwcm.town_hall_level = 6 then  1 end) as 'v6',\r\n\t\tsum(case when lwcm.town_hall_level = 7 then  1 end) as 'v7',\r\n\t\tsum(case when lwcm.town_hall_level = 8 then  1 end) as 'v8',\r\n\t\tsum(case when lwcm.town_hall_level = 9 then  1 end) as 'v9',\r\n\t\tsum(case when lwcm.town_hall_level = 10 then 1 end) as 'v10',\r\n\t\tsum(case when lwcm.town_hall_level = 11 then 1 end) as 'v11',\r\n\t\tsum(case when lwcm.town_hall_level = 12 then 1 end) as 'v12',\r\n\t\tsum(case when lwcm.town_hall_level = 13 then 1 end) as 'v13',\r\n\t\tsum(case when lwcm.town_hall_level = 14 then 1 end) as 'v14',\r\n\t\tsum(case when lwcm.town_hall_level = 1 then  1 end) as 'c1',\r\n\t\tsum(case when lwcm.town_hall_level = 2 then  1 end) as 'c2',\r\n\t\tsum(case when lwcm.town_hall_level = 3 then  1 end) as 'c3',\r\n\t\tsum(case when lwcm.town_hall_level = 4 then  1 end) as 'c4',\r\n\t\tsum(case when lwcm.town_hall_level = 5 then  1 end) as 'c5',\r\n\t\tsum(case when lwcm.town_hall_level = 6 then  1 end) as 'c6',\r\n\t\tsum(case when lwcm.town_hall_level = 7 then  1 end) as 'c7',\r\n\t\tsum(case when lwcm.town_hall_level = 8 then  1 end) as 'c8',\r\n\t\tsum(case when lwcm.town_hall_level = 9 then  1 end) as 'c9',\r\n\t\tsum(case when lwcm.town_hall_level = 10 then 1 end) as 'c10',\r\n\t\tsum(case when lwcm.town_hall_level = 11 then 1 end) as 'c11',\r\n\t\tsum(case when lwcm.town_hall_level = 12 then 1 end) as 'c12',\r\n\t\tsum(case when lwcm.town_hall_level = 13 then 1 end) as 'c13',\r\n\t\tsum(case when lwcm.town_hall_level = 14 then 1 end) as 'c14'\r\n\tfrom\r\n\t\t@ints i\r\n\t\tleft join league_war_clan_members lwcm2 on lwcm2.town_hall_level = i.ints\r\n\t\tleft join league_war_clans lwc2 on lwc2.id = lwcm2.league_war_clan_id\r\n\t\tleft join league_wars lw on lw.id = lwc2.league_war_id\r\n\t\tleft join league_war_details lwd on lwd.league_war_id = lw.id\r\n\t\tleft join league_war_clans lwc on lwc.league_war_id = lw.id and lwc2.id <> lwc.id\r\n\t\tleft join league_war_clan_members lwcm on lwcm.league_war_clan_id = lwc.id and lwcm.attack_defender_tag = lwcm2.tag\r\n\twhere\r\n\t\tlwc.tag in ($clans)\r\n\t\tand (lwcm.tag in (select tag from @latest_members) or '$onlycurrentmembers' = 'No' and lwcm.tag in ($players))\r\n\t\tand $__timeFilter(lwd.end_time)\r\n\t\tand lwcm.attack_attacker_tag is not null\r\n\tgroup by\r\n\t\ti.ints\r\nend\r\nif '$normalwars' = 'Yes' begin\r\n\tinsert into @values\r\n\tselect\r\n\t\tints as 'Defender',\r\n\t\tsum(case when wcm.town_hall_level = 1 then  1 end) as 'v1',\r\n\t\tsum(case when wcm.town_hall_level = 2 then  1 end) as 'v2',\r\n\t\tsum(case when wcm.town_hall_level = 3 then  1 end) as 'v3',\r\n\t\tsum(case when wcm.town_hall_level = 4 then  1 end) as 'v4',\r\n\t\tsum(case when wcm.town_hall_level = 5 then  1 end) as 'v5',\r\n\t\tsum(case when wcm.town_hall_level = 6 then  1 end) as 'v6',\r\n\t\tsum(case when wcm.town_hall_level = 7 then  1 end) as 'v7',\r\n\t\tsum(case when wcm.town_hall_level = 8 then  1 end) as 'v8',\r\n\t\tsum(case when wcm.town_hall_level = 9 then  1 end) as 'v9',\r\n\t\tsum(case when wcm.town_hall_level = 10 then 1 end) as 'v10',\r\n\t\tsum(case when wcm.town_hall_level = 11 then 1 end) as 'v11',\r\n\t\tsum(case when wcm.town_hall_level = 12 then 1 end) as 'v12',\r\n\t\tsum(case when wcm.town_hall_level = 13 then 1 end) as 'v13',\r\n\t\tsum(case when wcm.town_hall_level = 14 then 1 end) as 'v14',\r\n\t\tsum(case when wcm.town_hall_level = 1 then  1 end) as 'c1',\r\n\t\tsum(case when wcm.town_hall_level = 2 then  1 end) as 'c2',\r\n\t\tsum(case when wcm.town_hall_level = 3 then  1 end) as 'c3',\r\n\t\tsum(case when wcm.town_hall_level = 4 then  1 end) as 'c4',\r\n\t\tsum(case when wcm.town_hall_level = 5 then  1 end) as 'c5',\r\n\t\tsum(case when wcm.town_hall_level = 6 then  1 end) as 'c6',\r\n\t\tsum(case when wcm.town_hall_level = 7 then  1 end) as 'c7',\r\n\t\tsum(case when wcm.town_hall_level = 8 then  1 end) as 'c8',\r\n\t\tsum(case when wcm.town_hall_level = 9 then  1 end) as 'c9',\r\n\t\tsum(case when wcm.town_hall_level = 10 then 1 end) as 'c10',\r\n\t\tsum(case when wcm.town_hall_level = 11 then 1 end) as 'c11',\r\n\t\tsum(case when wcm.town_hall_level = 12 then 1 end) as 'c12',\r\n\t\tsum(case when wcm.town_hall_level = 13 then 1 end) as 'c13',\r\n\t\tsum(case when wcm.town_hall_level = 14 then 1 end) as 'c14'\r\n\tfrom\r\n\t\t@ints i\r\n\t\tleft join war_clan_members wcm2 on wcm2.town_hall_level = i.ints\r\n\t\tleft join war_clans wc2 on wc2.id = wcm2.war_clan_id\r\n\t\tleft join wars w on w.id = wc2.war_id\r\n\t\tleft join war_clans wc on wc.war_id = w.id and wc2.id <> wc.id\r\n\t\tleft join war_clan_members wcm on wcm.war_clan_id = wc.id\r\n\t\tleft join war_attacks wa on wa.war_clan_member_id = wcm.id and wa.defender_tag = wcm2.tag\r\n\twhere\r\n\t\twc.tag in ($clans)\r\n\t\tand (wcm.tag in (select tag from @latest_members) or '$onlycurrentmembers' = 'No' and wcm.tag in ($players))\r\n\t\tand $__timeFilter(w.end_time)\r\n\t\tand wa.attacker_tag is not null\r\n\tgroup by\r\n\t\ti.ints\r\nend\r\n\r\nselect\r\n\ti.ints as 'Defender',\r\n\tsum(v.v1) as  '1',\r\n\tsum(v.v2) as  '2',\r\n\tsum(v.v3) as  '3',\r\n\tsum(v.v4) as  '4',\r\n\tsum(v.v5) as  '5',\r\n\tsum(v.v6) as  '6',\r\n\tsum(v.v7) as  '7',\r\n\tsum(v.v8) as  '8',\r\n\tsum(v.v9) as  '9',\r\n\tsum(v.v10) as '10',\r\n\tsum(v.v11) as '11',\r\n\tsum(v.v12) as '12',\r\n\tsum(v.v13) as '13',\r\n\tsum(v.v14) as '14'\r\nfrom\r\n\t@ints i\r\n\tleft join @values v on v.ints = i.ints\r\ngroup by\r\n\ti.ints"
      }
     ]
    },
    {
     "title": "Stars",
     "type": "table",
     "gridPos": { "h": 15, "w": 12, "x": 12, "y": 7 },
     "targets": [
      {
       "rawSql": "declare @latest_request_id int = (select top 1 id from requests order by timestamp desc)\r\ndeclare @latest_members table (tag nvarchar(16), name nvarchar(256))\r\ninsert into @latest_members\r\nselect\r\n\tm.tag,\r\n\tm.name\r\nfrom\r\n\trequests r\r\n\tjoin clans c on c.request_id = r.id\r\n\tjoin members m on m.clan_id = c.id\r\nwhere\r\n\tc.tag in ($clans)\r\n\tand m.tag in ($players)\r\n\tand r.id = @latest_request_id\r\n\t\r\ndeclare @ints table (ints int)\r\ninsert into @ints (ints) values (1), (2), (3), (4), (5), (6), (7), (8), (9), (10), (11), (12), (13), (14)\r\n\r\ndeclare @values table (\r\n\tints int,\r\n\tv1 int, v2 int, v3 int, v4 int, v5 int, v6 int, v7 int, v8 int, v9 int, v10 int, v11 int, v12 int, v13 int, v14 int,\r\n\tc1 int, c2 int, c3 int, c4 int, c5 int, c6 int, c7 int, c8 int, c9 int, c10 int, c11 int, c12 int, c13 int, c14 int\r\n)\r\n\r\nif '$warleagues' = 'Yes' begin\r\n\tinsert into @values\r\n\tselect\r\n\t\tints as 'Defender',\r\n\t\tsum(case when lwcm.town_hall_level = 1 then  lwcm.attack_stars end) as 'v1',\r\n\t\tsum(case when lwcm.town_hall_level = 2 then  lwcm.attack_stars end) as 'v2',\r\n\t\tsum(case when lwcm.town_hall_level = 3 then  lwcm.attack_stars end) as 'v3',\r\n\t\tsum(case when lwcm.town_hall_level = 4 then  lwcm.attack_stars end) as 'v4',\r\n\t\tsum(case when lwcm.town_hall_level = 5 then  lwcm.attack_stars end) as 'v5',\r\n\t\tsum(case when lwcm.town_hall_level = 6 then  lwcm.attack_stars end) as 'v6',\r\n\t\tsum(case when lwcm.town_hall_level = 7 then  lwcm.attack_stars end) as 'v7',\r\n\t\tsum(case when lwcm.town_hall_level = 8 then  lwcm.attack_stars end) as 'v8',\r\n\t\tsum(case when lwcm.town_hall_level = 9 then  lwcm.attack_stars end) as 'v9',\r\n\t\tsum(case when lwcm.town_hall_level = 10 then lwcm.attack_stars end) as 'v10',\r\n\t\tsum(case when lwcm.town_hall_level = 11 then lwcm.attack_stars end) as 'v11',\r\n\t\tsum(case when lwcm.town_hall_level = 12 then lwcm.attack_stars end) as 'v12',\r\n\t\tsum(case when lwcm.town_hall_level = 13 then lwcm.attack_stars end) as 'v13',\r\n\t\tsum(case when lwcm.town_hall_level = 14 then lwcm.attack_stars end) as 'v14',\r\n\t\tsum(case when lwcm.town_hall_level = 1 then  1 end) as 'c1',\r\n\t\tsum(case when lwcm.town_hall_level = 2 then  1 end) as 'c2',\r\n\t\tsum(case when lwcm.town_hall_level = 3 then  1 end) as 'c3',\r\n\t\tsum(case when lwcm.town_hall_level = 4 then  1 end) as 'c4',\r\n\t\tsum(case when lwcm.town_hall_level = 5 then  1 end) as 'c5',\r\n\t\tsum(case when lwcm.town_hall_level = 6 then  1 end) as 'c6',\r\n\t\tsum(case when lwcm.town_hall_level = 7 then  1 end) as 'c7',\r\n\t\tsum(case when lwcm.town_hall_level = 8 then  1 end) as 'c8',\r\n\t\tsum(case when lwcm.town_hall_level = 9 then  1 end) as 'c9',\r\n\t\tsum(case when lwcm.town_hall_level = 10 then 1 end) as 'c10',\r\n\t\tsum(case when lwcm.town_hall_level = 11 then 1 end) as 'c11',\r\n\t\tsum(case when lwcm.town_hall_level = 12 then 1 end) as 'c12',\r\n\t\tsum(case when lwcm.town_hall_level = 13 then 1 end) as 'c13',\r\n\t\tsum(case when lwcm.town_hall_level = 14 then 1 end) as 'c14'\r\n\tfrom\r\n\t\t@ints i\r\n\t\tleft join league_war_clan_members lwcm2 on lwcm2.town_hall_level = i.ints\r\n\t\tleft join league_war_clans lwc2 on lwc2.id = lwcm2.league_war_clan_id\r\n\t\tleft join league_wars lw on lw.id = lwc2.league_war_id\r\n\t\tleft join league_war_details lwd on lwd.league_war_id = lw.id\r\n\t\tleft join league_war_clans lwc on lwc.league_war_id = lw.id and lwc2.id <> lwc.id\r\n\t\tleft join league_war_clan_members lwcm on lwcm.league_war_clan_id = lwc.id and lwcm.attack_defender_tag = lwcm2.tag\r\n\twhere\r\n\t\tlwc.tag in ($clans)\r\n\t\tand (lwcm.tag in (select tag from @latest_members) or '$onlycurrentmembers' = 'No' and lwcm.tag in ($players))\r\n\t\tand $__timeFilter(lwd.end_time)\r\n\t\tand lwcm.attack_attacker_tag is not null\r\n\tgroup by\r\n\t\ti.ints\r\nend\r\nif '$normalwars' = 'Yes' begin\r\n\tinsert into @values\r\n\tselect\r\n\t\tints as 'Defender',\r\n\t\tsum(case when wcm.town_hall_level = 1 then  wa.stars end) as 'v1',\r\n\t\tsum(case when wcm.town_hall_level = 2 then  wa.stars end) as 'v2',\r\n\t\tsum(case when wcm.town_hall_level = 3 then  wa.stars end) as 'v3',\r\n\t\tsum(case when wcm.town_hall_level = 4 then  wa.stars end) as 'v4',\r\n\t\tsum(case when wcm.town_hall_level = 5 then  wa.stars end) as 'v5',\r\n\t\tsum(case when wcm.town_hall_level = 6 then  wa.stars end) as 'v6',\r\n\t\tsum(case when wcm.town_hall_level = 7 then  wa.stars end) as 'v7',\r\n\t\tsum(case when wcm.town_hall_level = 8 then  wa.stars end) as 'v8',\r\n\t\tsum(case when wcm.town_hall_level = 9 then  wa.stars end) as 'v9',\r\n\t\tsum(case when wcm.town_hall_level = 10 then wa.stars end) as 'v10',\r\n\t\tsum(case when wcm.town_hall_level = 11 then wa.stars end) as 'v11',\r\n\t\tsum(case when wcm.town_hall_level = 12 then wa.stars end) as 'v12',\r\n\t\tsum(case when wcm.town_hall_level = 13 then wa.stars end) as 'v13',\r\n\t\tsum(case when wcm.town_hall_level = 14 then wa.stars end) as 'v14',\r\n\t\tsum(case when wcm.town_hall_level = 1 then  1 end) as 'c1',\r\n\t\tsum(case when wcm.town_hall_level = 2 then  1 end) as 'c2',\r\n\t\tsum(case when wcm.town_hall_level = 3 then  1 end) as 'c3',\r\n\t\tsum(case when wcm.town_hall_level = 4 then  1 end) as 'c4',\r\n\t\tsum(case when wcm.town_hall_level = 5 then  1 end) as 'c5',\r\n\t\tsum(case when wcm.town_hall_level = 6 then  1 end) as 'c6',\r\n\t\tsum(case when wcm.town_hall_level = 7 then  1 end) as 'c7',\r\n\t\tsum(case when wcm.town_hall_level = 8 then  1 end) as 'c8',\r\n\t\tsum(case when wcm.town_hall_level = 9 then  1 end) as 'c9',\r\n\t\tsum(case when wcm.town_hall_level = 10 then 1 end) as 'c10',\r\n\t\tsum(case when wcm.town_hall_level = 11 then 1 end) as 'c11',\r\n\t\tsum(case when wcm.town_hall_level = 12 then 1 end) as 'c12',\r\n\t\tsum(case when wcm.town_hall_level = 13 then 1 end) as 'c13',\r\n\t\tsum(case when wcm.town_hall_level = 14 then 1 end) as 'c14'\r\n\tfrom\r\n\t\t@ints i\r\n\t\tleft join war_clan_members wcm2 on wcm2.town_hall_level = i.ints\r\n\t\tleft join war_clans wc2 on wc2.id = wcm2.war_clan_id\r\n\t\tleft join wars w on w.id = wc2.war_id\r\n\t\tleft join war_clans wc on wc.war_id = w.id and wc2.id <> wc.id\r\n\t\tleft join war_clan_members wcm on wcm.war_clan_id = wc.id\r\n\t\tleft join war_attacks wa on wa.war_clan_member_id = wcm.id and wa.defender_tag = wcm2.tag\r\n\twhere\r\n\t\twc.tag in ($clans)\r\n\t\tand (wcm.tag in (select tag from @latest_members) or '$onlycurrentmembers' = 'No' and wcm.tag in ($players))\r\n\t\tand $__timeFilter(w.end_time)\r\n\t\tand wa.attacker_tag is not null\r\n\tgroup by\r\n\t\ti.ints\r\nend\r\n\r\nselect\r\n\ti.ints as 'Defender',\r\n\tsum(v.v1)  / cast(sum(v.c1)  as float) as  '1',\r\n\tsum(v.v2)  / cast(sum(v.c2)  as float) as  '2',\r\n\tsum(v.v3)  / cast(sum(v.c3)  as float) as  '3',\r\n\tsum(v.v4)  / cast(sum(v.c4)  as float) as  '4',\r\n\tsum(v.v5)  / cast(sum(v.c5)  as float) as  '5',\r\n\tsum(v.v6)  / cast(sum(v.c6)  as float) as  '6',\r\n\tsum(v.v7)  / cast(sum(v.c7)  as float) as  '7',\r\n\tsum(v.v8)  / cast(sum(v.c8)  as float) as  '8',\r\n\tsum(v.v9)  / cast(sum(v.c9)  as float) as  '9',\r\n\tsum(v.v10) / cast(sum(v.c10) as float) as '10',\r\n\tsum(v.v11) / cast(sum(v.c11) as float) as '11',\r\n\tsum(v.v12) / cast(sum(v.c12) as float) as '12',\r\n\tsum(v.v13) / cast(sum(v.c13) as float) as '13',\r\n\tsum(v.v14) / cast(sum(v.c14) as float) as '14'\r\nfrom\r\n\t@ints i\r\n\tleft join @values v on v.ints = i.ints\r\ngroup by\r\n\ti.ints"
      }
     ]
    },
    {
     "title": "Destruction",
     "type": "table",
     "gridPos": { "h": 15, "w": 12, "x": 0, "y": 22 },
     "targets": [
      {
       "rawSql": "declare @latest_request_id int = (select top 1 id from requests order by timestamp desc)\r\ndeclare @latest_members table (tag nvarchar(16), name nvarchar(256))\r\ninsert into @latest_members\r\nselect\r\n\tm.tag,\r\n\tm.name\r\nfrom\r\n\trequests r\r\n\tjoin clans c on c.request_id = r.id\r\n\tjoin members m on m.clan_id = c.id\r\nwhere\r\n\tc.tag in ($clans)\r\n\tand m.tag in ($players)\r\n\tand r.id = @latest_request_id\r\n\t\r\ndeclare @ints table (ints int)\r\ninsert into @ints (ints) values (1), (2), (3), (4), (5), (6), (7), (8), (9), (10), (11), (12), (13), (14)\r\n\r\ndeclare @values table (\r\n\tints int,\r\n\tv1 int, v2 int, v3 int, v4 int, v5 int, v6 int, v7 int, v8 int, v9 int, v10 int, v11 int, v12 int, v13 int, v14 int,\r\n\tc1 int, c2 int, c3 int, c4 int, c5 int, c6 int, c7 int, c8 int, c9 int, c10 int, c11 int, c12 int, c13 int, c14 int\r\n)\r\n\r\nif '$warleagues' = 'Yes' begin\r\n\tinsert into @values\r\n\tselect\r\n\t\tints as 'Defender',\r\n\t\tsum(case when lwcm.town_hall_level = 1 then  lwcm.attack_destruction_percentage end) as 'v1',\r\n\t\tsum(case when lwcm.town_hall_level = 2 then  lwcm.attack_destruction_percentage end) as 'v2',\r\n\t\tsum(case when lwcm.town_hall_level = 3 then  lwcm.attack_destruction_percentage end) as 'v3',\r\n\t\tsum(case when lwcm.town_hall_level = 4 then  lwcm.attack_destruction_percentage end) as 'v4',\r\n\t\tsum(case when lwcm.town_hall_level = 5 then  lwcm.attack_destruction_percentage end) as 'v5',\r\n\t\tsum(case when lwcm.town_hall_level = 6 then  lwcm.attack_destruction_percentage end) as 'v6',\r\n\t\tsum(case when lwcm.town_hall_level = 7 then  lwcm.attack_destruction_percentage end) as 'v7',\r\n\t\tsum(case when lwcm.town_hall_level = 8 then  lwcm.attack_destruction_percentage end) as 'v8',\r\n\t\tsum(case when lwcm.town_hall_level = 9 then  lwcm.attack_destruction_percentage end) as 'v9',\r\n\t\tsum(case when lwcm.town_hall_level = 10 then lwcm.attack_destruction_percentage end) as 'v10',\r\n\t\tsum(case when lwcm.town_hall_level = 11 then lwcm.attack_destruction_percentage end) as 'v11',\r\n\t\tsum(case when lwcm.town_hall_level = 12 then lwcm.attack_destruction_percentage end) as 'v12',\r\n\t\tsum(case when lwcm.town_hall_level = 13 then lwcm.attack_destruction_percentage end) as 'v13',\r\n\t\tsum(case when lwcm.town_hall_level = 14 then lwcm.attack_destruction_percentage end) as 'v14',\r\n\t\tsum(case when lwcm.town_hall_level = 1 then  1 end) as 'c1',\r\n\t\tsum(case when lwcm.town_hall_level = 2 then  1 end) as 'c2',\r\n\t\tsum(case when lwcm.town_hall_level = 3 then  1 end) as 'c3',\r\n\t\tsum(case when lwcm.town_hall_level = 4 then  1 end) as 'c4',\r\n\t\tsum(case when lwcm.town_hall_level = 5 then  1 end) as 'c5',\r\n\t\tsum(case when lwcm.town_hall_level = 6 then  1 end) as 'c6',\r\n\t\tsum(case when lwcm.town_hall_level = 7 then  1 end) as 'c7',\r\n\t\tsum(case when lwcm.town_hall_level = 8 then  1 end) as 'c8',\r\n\t\tsum(case when lwcm.town_hall_level = 9 then  1 end) as 'c9',\r\n\t\tsum(case when lwcm.town_hall_level = 10 then 1 end) as 'c10',\r\n\t\tsum(case when lwcm.town_hall_level = 11 then 1 end) as 'c11',\r\n\t\tsum(case when lwcm.town_hall_level = 12 then 1 end) as 'c12',\r\n\t\tsum(case when lwcm.town_hall_level = 13 then 1 end) as 'c13',\r\n\t\tsum(case when lwcm.town_hall_level = 14 then 1 end) as 'c14'\r\n\tfrom\r\n\t\t@ints i\r\n\t\tleft join league_war_clan_members lwcm2 on lwcm2.town_hall_level = i.ints\r\n\t\tleft join league_war_clans lwc2 on lwc2.id = lwcm2.league_war_clan_id\r\n\t\tleft join league_wars lw on lw.id = lwc2.league_war_id\r\n\t\tleft join league_war_details lwd on lwd.league_war_id = lw.id\r\n\t\tleft join league_war_clans lwc on lwc.league_war_id = lw.id and lwc2.id <> lwc.id\r\n\t\tleft join league_war_clan_members lwcm on lwcm.league_war_clan_id = lwc.id and lwcm.attack_defender_tag = lwcm2.tag\r\n\twhere\r\n\t\tlwc.tag in ($clans)\r\n\t\tand (lwcm.tag in (select tag from @latest_members) or '$onlycurrentmembers' = 'No' and lwcm.tag in ($players))\r\n\t\tand $__timeFilter(lwd.end_time)\r\n\t\tand lwcm.attack_attacker_tag is not null\r\n\tgroup by\r\n\t\ti.ints\r\nend\r\nif '$normalwars' = 'Yes' begin\r\n\tinsert into @values\r\n\tselect\r\n\t\tints as 'Defender',\r\n\t\tsum(case when wcm.town_hall_level = 1 then  wa.destruction_percentage end) as 'v1',\r\n\t\tsum(case when wcm.town_hall_level = 2 then  wa.destruction_percentage end) as 'v2',\r\n\t\tsum(case when wcm.town_hall_level = 3 then  wa.destruction_percentage end) as 'v3',\r\n\t\tsum(case when wcm.town_hall_level = 4 then  wa.destruction_percentage end) as 'v4',\r\n\t\tsum(case when wcm.town_hall_level = 5 then  wa.destruction_percentage end) as 'v5',\r\n\t\tsum(case when wcm.town_hall_level = 6 then  wa.destruction_percentage end) as 'v6',\r\n\t\tsum(case when wcm.town_hall_level = 7 then  wa.destruction_percentage end) as 'v7',\r\n\t\tsum(case when wcm.town_hall_level = 8 then  wa.destruction_percentage end) as 'v8',\r\n\t\tsum(case when wcm.town_hall_level = 9 then  wa.destruction_percentage end) as 'v9',\r\n\t\tsum(case when wcm.town_hall_level = 10 then wa.destruction_percentage end) as 'v10',\r\n\t\tsum(case when wcm.town_hall_level = 11 then wa.destruction_percentage end) as 'v11',\r\n\t\tsum(case when wcm.town_hall_level = 12 then wa.destruction_percentage end) as 'v12',\r\n\t\tsum(case when wcm.town_hall_level = 13 then wa.destruction_percentage end) as 'v13',\r\n\t\tsum(case when wcm.town_hall_level = 14 then wa.destruction_percentage end) as 'v14',\r\n\t\tsum(case when wcm.town_hall_level = 1 then  1 end) as 'c1',\r\n\t\tsum(case when wcm.town_hall_level = 2 then  1 end) as 'c2',\r\n\t\tsum(case when wcm.town_hall_level = 3 then  1 end) as 'c3',\r\n\t\tsum(case when wcm.town_hall_level = 4 then  1 end) as 'c4',\r\n\t\tsum(case when wcm.town_hall_level = 5 then  1 end) as 'c5',\r\n\t\tsum(case when wcm.town_hall_level = 6 then  1 end) as 'c6',\r\n\t\tsum(case when wcm.town_hall_level = 7 then  1 end) as 'c7',\r\n\t\tsum(case when wcm.town_hall_level = 8 then  1 end) as 'c8',\r\n\t\tsum(case when wcm.town_hall_level = 9 then  1 end) as 'c9',\r\n\t\tsum(case when wcm.town_hall_level = 10 then 1 end) as 'c10',\r\n\t\tsum(case when wcm.town_hall_level = 11 then 1 end) as 'c11',\r\n\t\tsum(case when wcm.town_hall_level = 12 then 1 end) as 'c12',\r\n\t\tsum(case when wcm.town_hall_level = 13 then 1 end) as 'c13',\r\n\t\tsum(case when wcm.town_hall_level = 14 then 1 end) as 'c14'\r\n\tfrom\r\n\t\t@ints i\r\n\t\tleft join war_clan_members wcm2 on wcm2.town_hall_level = i.ints\r\n\t\tleft join war_clans wc2 on wc2.id = wcm2.war_clan_id\r\n\t\tleft join wars w on w.id = wc2.war_id\r\n\t\tleft join war_clans wc on wc.war_id = w.id and wc2.id <> wc.id\r\n\t\tleft join war_clan_members wcm on wcm.war_clan_id = wc.id\r\n\t\tleft join war_attacks wa on wa.war_clan_member_id = wcm.id and wa.defender_tag = wcm2.tag\r\n\twhere\r\n\t\twc.tag in ($clans)\r\n\t\tand (wcm.tag in (select tag from @latest_members) or '$onlycurrentmembers' = 'No' and wcm.tag in ($players))\r\n\t\tand $__timeFilter(w.end_time)\r\n\t\tand wa.attacker_tag is not null\r\n\tgroup by\r\n\t\ti.ints\r\nend\r\n\r\nselect\r\n\ti.ints as 'Defender',\r\n\tsum(v.v1)  / cast(sum(v.c1)  as float) as  '1',\r\n\tsum(v.v2)  / cast(sum(v.c2)  as float) as  '2',\r\n\tsum(v.v3)  / cast(sum(v.c3)  as float) as  '3',\r\n\tsum(v.v4)  / cast(sum(v.c4)  as float) as  '4',\r\n\tsum(v.v5)  / cast(sum(v.c5)  as float) as  '5',\r\n\tsum(v.v6)  / cast(sum(v.c6)  as float) as  '6',\r\n\tsum(v.v7)  / cast(sum(v.c7)  as float) as  '7',\r\n\tsum(v.v8)  / cast(sum(v.c8)  as float) as  '8',\r\n\tsum(v.v9)  / cast(sum(v.c9)  as float) as  '9',\r\n\tsum(v.v10) / cast(sum(v.c10) as float) as '10',\r\n\tsum(v.v11) / cast(sum(v.c11) as float) as '11',\r\n\tsum(v.v12) / cast(sum(v.c12) as float) as '12',\r\n\tsum(v.v13) / cast(sum(v.c13) as float) as '13',\r\n\tsum(v.v14) / cast(sum(v.c14) as float) as '14'\r\nfrom\r\n\t@ints i\r\n\tleft join @values v on v.ints = i.ints\r\ngroup by\r\n\ti.ints"
      }
     ]
    }
   ]
  },
  {
   "title": "Attacks by Townhall diff",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Count",
     "type": "table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 8 },
     "targets": [
      {
       "rawSql": "declare @latest_request_id int = (select top 1 id from requests order by timestamp desc)\r\ndeclare @latest_members table (tag nvarchar(16), name nvarchar(256))\r\ninsert into @latest_members\r\nselect\r\n\tm.tag,\r\n\tm.name\r\nfrom\r\n\trequests r\r\n\tjoin clans c on c.request_id = r.id\r\n\tjoin members m on m.clan_id = c.id\r\nwhere\r\n\tc.tag in ($clans)\r\n\tand m.tag in ($players)\r\n\tand r.id = @latest_request_id\r\n\t\r\ndeclare @attack_table table (townhall_diff int, [count] int, total_stars int, total_destruction int)\r\n\r\nif '$warleagues' = 'Yes' begin\r\n\tinsert into @attack_table\r\n\tselect\r\n\t\tlwcm2.town_hall_level - lwcm.town_hall_level as townhall_diff,\r\n\t\tcount(1) as [count],\r\n\t\tsum(lwcm.attack_stars) as total_stars,\r\n\t\tsum(lwcm.attack_destruction_percentage) as total_destruction\r\n\tfrom\r\n\t\tleague_wars lw\r\n\t\tjoin league_war_details lwd on lwd.league_war_id = lw.id\r\n\t\tjoin league_war_clans lwc on lwc.league_war_id = lw.id\r\n\t\tjoin league_war_clan_members lwcm on lwcm.league_war_clan_id = lwc.id\r\n\t\tjoin league_war_clans lwc2 on lwc2.league_war_id = lw.id and lwc2.id <> lwc.id\r\n\t\tjoin league_war_clan_members lwcm2 on lwcm2.league_war_clan_id = lwc2.id and lwcm.attack_defender_tag = lwcm2.tag\r\n\twhere\r\n\t\tlwc.tag in ($clans)\r\n\t\tand (lwcm.tag in (select tag from @latest_members) or '$onlycurrentmembers' = 'No' and lwcm.tag in ($players))\r\n\t\tand $__timeFilter(lwd.end_time)\r\n\tgroup by\r\n\t\tlwcm2.town_hall_level - lwcm.town_hall_level\r\nend\r\nif '$normalwars' = 'Yes' begin\r\n\tinsert into @attack_table\r\n\tselect\r\n\t\twcm2.town_hall_level - wcm.town_hall_level as townhall_diff,\r\n\t\tcount(1) as [count],\r\n\t\tsum(wa.stars) as total_stars,\r\n\t\tsum(wa.destruction_percentage) as total_destruction\r\n\tfrom\r\n\t\twars w\r\n\t\tjoin war_clans wc on wc.war_id = w.id\r\n\t\tjoin war_clan_members wcm on wcm.war_clan_id = wc.id\r\n\t\tjoin war_attacks wa on wa.war_clan_member_id = wcm.id\r\n\t\tjoin war_clans wc2 on wc2.war_id = w.id and wc2.id <> wc.id\r\n\t\tjoin war_clan_members wcm2 on wcm2.war_clan_id = wc2.id and wa.defender_tag = wcm2.tag\r\n\twhere\r\n\t\twc.tag in ($clans)\r\n\t\tand (wcm.tag in (select tag from @latest_members) or '$onlycurrentmembers' = 'No' and wcm.tag in ($players))\r\n\t\tand $__timeFilter(w.end_time)\r\n\tgroup by\r\n\t\twcm2.town_hall_level - wcm.town_hall_level\r\nend\r\n\r\nselect\r\n\ttownhall_diff as 'Townhall diff',\r\n\tsum([count]) as 'Count',\r\n\tsum(total_stars) / cast(sum([count]) as float) as 'Stars',\r\n\tsum(total_destruction) / cast(sum([count]) as float) as 'Destruction'\r\nfrom\r\n\t@attack_table\r\ngroup by\r\n\ttownhall_diff"
      }
     ]
    },
    {
     "title": "Count",
     "type": "michaeldmoore-scatter-panel",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 19 },
     "targets": [
      {
       "rawSql": "declare @latest_request_id int = (select top 1 id from requests order by timestamp desc)\r\ndeclare @latest_members table (tag nvarchar(16), name nvarchar(256))\r\ninsert into @latest_members\r\nselect\r\n\tm.tag,\r\n\tm.name\r\nfrom\r\n\trequests r\r\n\tjoin clans c on c.request_id = r.id\r\n\tjoin members m on m.clan_id = c.id\r\nwhere\r\n\tc.tag in ($clans)\r\n\tand m.tag in ($players)\r\n\tand r.id = @latest_request_id\r\n\t\r\ndeclare @attack_table table (townhall_diff int, [count] int, total_stars int, total_destruction int)\r\n\r\nif '$warleagues' = 'Yes' begin\r\n\tinsert into @attack_table\r\n\tselect\r\n\t\tlwcm2.town_hall_level - lwcm.town_hall_level as townhall_diff,\r\n\t\tcount(1) as [count],\r\n\t\tsum(lwcm.attack_stars) as total_stars,\r\n\t\tsum(lwcm.attack_destruction_percentage) as total_destruction\r\n\tfrom\r\n\t\tleague_wars lw\r\n\t\tjoin league_war_details lwd on lwd.league_war_id = lw.id\r\n\t\tjoin league_war_clans lwc on lwc.league_war_id = lw.id\r\n\t\tjoin league_war_clan_members lwcm on lwcm.league_war_clan_id = lwc.id\r\n\t\tjoin league_war_clans lwc2 on lwc2.league_war_id = lw.id and lwc2.id <> lwc.id\r\n\t\tjoin league_war_clan_members lwcm2 on lwcm2.league_war_clan_id = lwc2.id and lwcm.attack_defender_tag = lwcm2.tag\r\n\twhere\r\n\t\tlwc.tag in ($clans)\r\n\t\tand (lwcm.tag in (select tag from @latest_members) or '$onlycurrentmembers' = 'No' and lwcm.tag in ($players))\r\n\t\tand $__timeFilter(lwd.end_time)\r\n\tgroup by\r\n\t\tlwcm2.town_hall_level - lwcm.town_hall_level\r\nend\r\nif '$normalwars' = 'Yes' begin\r\n\tinsert into @attack_table\r\n\tselect\r\n\t\twcm2.town_hall_level - wcm.town_hall_level as townhall_diff,\r\n\t\tcount(1) as [count],\r\n\t\tsum(wa.stars) as total_stars,\r\n\t\tsum(wa.destruction_percentage) as total_destruction\r\n\tfrom\r\n\t\twars w\r\n\t\tjoin war_clans wc on wc.war_id = w.id\r\n\t\tjoin war_clan_members wcm on wcm.war_clan_id = wc.id\r\n\t\tjoin war_attacks wa on wa.war_clan_member_id = wcm.id\r\n\t\tjoin war_clans wc2 on wc2.war_id = w.id and wc2.id <> wc.id\r\n\t\tjoin war_clan_members wcm2 on wcm2.war_clan_id = wc2.id and wa.defender_tag = wcm2.tag\r\n\twhere\r\n\t\twc.tag in ($clans)\r\n\t\tand (wcm.tag in (select tag from @latest_members) or '$onlycurrentmembers' = 'No' and wcm.tag in ($players))\r\n\t\tand $__timeFilter(w.end_time)\r\n\tgroup by\r\n\t\twcm2.town_hall_level - wcm.town_hall_level\r\nend\r\n\r\nselect\r\n\ttownhall_diff as 'Townhall diff',\r\n\tsum([count]) as 'Count'\r\nfrom\r\n\t@attack_table\r\ngroup by\r\n\ttownhall_diff\r\norder by\r\n\ttownhall_diff asc"
      }
     ]
    },
    {
     "title": "Stars",
     "type": "michaeldmoore-scatter-panel",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 19 },
     "targets": [
      {
       "rawSql": "declare @latest_request_id int = (select top 1 id from requests order by timestamp desc)\r\ndeclare @latest_members table (tag nvarchar(16), name nvarchar(256))\r\ninsert into @latest_members\r\nselect\r\n\tm.tag,\r\n\tm.name\r\nfrom\r\n\trequests r\r\n\tjoin clans c on c.request_id = r.id\r\n\tjoin members m on m.clan_id = c.id\r\nwhere\r\n\tc.tag in ($clans)\r\n\tand m.tag in ($players)\r\n\tand r.id = @latest_request_id\r\n\t\r\ndeclare @attack_table table (townhall_diff int, [count] int, total_stars int, total_destruction int)\r\n\r\nif '$warleagues' = 'Yes' begin\r\n\tinsert into @attack_table\r\n\tselect\r\n\t\tlwcm2.town_hall_level - lwcm.town_hall_level as townhall_diff,\r\n\t\tcount(1) as [count],\r\n\t\tsum(lwcm.attack_stars) as total_stars,\r\n\t\tsum(lwcm.attack_destruction_percentage) as total_destruction\r\n\tfrom\r\n\t\tleague_wars lw\r\n\t\tjoin league_war_details lwd on lwd.league_war_id = lw.id\r\n\t\tjoin league_war_clans lwc on lwc.league_war_id = lw.id\r\n\t\tjoin league_war_clan_members lwcm on lwcm.league_war_clan_id = lwc.id\r\n\t\tjoin league_war_clans lwc2 on lwc2.league_war_id = lw.id and lwc2.id <> lwc.id\r\n\t\tjoin league_war_clan_members lwcm2 on lwcm2.league_war_clan_id = lwc2.id and lwcm.attack_defender_tag = lwcm2.tag\r\n\twhere\r\n\t\tlwc.tag in ($clans)\r\n\t\tand (lwcm.tag in (select tag from @latest_members) or '$onlycurrentmembers' = 'No' and lwcm.tag in ($players))\r\n\t\tand $__timeFilter(lwd.end_time)\r\n\tgroup by\r\n\t\tlwcm2.town_hall_level - lwcm.town_hall_level\r\nend\r\nif '$normalwars' = 'Yes' begin\r\n\tinsert into @attack_table\r\n\tselect\r\n\t\twcm2.town_hall_level - wcm.town_hall_level as townhall_diff,\r\n\t\tcount(1) as [count],\r\n\t\tsum(wa.stars) as total_stars,\r\n\t\tsum(wa.destruction_percentage) as total_destruction\r\n\tfrom\r\n\t\twars w\r\n\t\tjoin war_clans wc on wc.war_id = w.id\r\n\t\tjoin war_clan_members wcm on wcm.war_clan_id = wc.id\r\n\t\tjoin war_attacks wa on wa.war_clan_member_id = wcm.id\r\n\t\tjoin war_clans wc2 on wc2.war_id = w.id and wc2.id <> wc.id\r\n\t\tjoin war_clan_members wcm2 on wcm2.war_clan_id = wc2.id and wa.defender_tag = wcm2.tag\r\n\twhere\r\n\t\twc.tag in ($clans)\r\n\t\tand (wcm.tag in (select tag from @latest_members) or '$onlycurrentmembers' = 'No' and wcm.tag in ($players))\r\n\t\tand $__timeFilter(w.end_time)\r\n\tgroup by\r\n\t\twcm2.town_hall_level - wcm.town_hall_level\r\nend\r\n\r\nselect\r\n\ttownhall_diff as 'Townhall diff',\r\n\tsum(total_stars) / cast(sum([count]) as float) as 'Stars'\r\nfrom\r\n\t@attack_table\r\ngroup by\r\n\ttownhall_diff\r\norder by\r\n\ttownhall_diff asc"
      }
     ]
    },
    {
     "title": "Destruction",
     "type": "michaeldmoore-scatter-panel",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 19 },
     "targets": [
      {
       "rawSql": "declare @latest_request_id int = (select top 1 id from requests order by timestamp desc)\r\ndeclare @latest_members table (tag nvarchar(16), name nvarchar(256))\r\ninsert into @latest_members\r\nselect\r\n\tm.tag,\r\n\tm.name\r\nfrom\r\n\trequests r\r\n\tjoin clans c on c.request_id = r.id\r\n\tjoin members m on m.clan_id = c.id\r\nwhere\r\n\tc.tag in ($clans)\r\n\tand m.tag in ($players)\r\n\tand r.id = @latest_request_id\r\n\t\r\ndeclare @attack_table table (townhall_diff int, [count] int, total_stars int, total_destruction int)\r\n\r\nif '$warleagues' = 'Yes' begin\r\n\tinsert into @attack_table\r\n\tselect\r\n\t\tlwcm2.town_hall_level - lwcm.town_hall_level as townhall_diff,\r\n\t\tcount(1) as [count],\r\n\t\tsum(lwcm.attack_stars) as total_stars,\r\n\t\tsum(lwcm.attack_destruction_percentage) as total_destruction\r\n\tfrom\r\n\t\tleague_wars lw\r\n\t\tjoin league_war_details lwd on lwd.league_war_id = lw.id\r\n\t\tjoin league_war_clans lwc on lwc.league_war_id = lw.id\r\n\t\tjoin league_war_clan_members lwcm on lwcm.league_war_clan_id = lwc.id\r\n\t\tjoin league_war_clans lwc2 on lwc2.league_war_id = lw.id and lwc2.id <> lwc.id\r\n\t\tjoin league_war_clan_members lwcm2 on lwcm2.league_war_clan_id = lwc2.id and lwcm.attack_defender_tag = lwcm2.tag\r\n\twhere\r\n\t\tlwc.tag in ($clans)\r\n\t\tand (lwcm.tag in (select tag from @latest_members) or '$onlycurrentmembers' = 'No' and lwcm.tag in ($players))\r\n\t\tand $__timeFilter(lwd.end_time)\r\n\tgroup by\r\n\t\tlwcm2.town_hall_level - lwcm.town_hall_level\r\nend\r\nif '$normalwars' = 'Yes' begin\r\n\tinsert into @attack_table\r\n\tselect\r\n\t\twcm2.town_hall_level - wcm.town_hall_level as townhall_diff,\r\n\t\tcount(1) as [count],\r\n\t\tsum(wa.stars) as total_stars,\r\n\t\tsum(wa.destruction_percentage) as total_destruction\r\n\tfrom\r\n\t\twars w\r\n\t\tjoin war_clans wc on wc.war_id = w.id\r\n\t\tjoin war_clan_members wcm on wcm.war_clan_id = wc.id\r\n\t\tjoin war_attacks wa on wa.war_clan_member_id = wcm.id\r\n\t\tjoin war_clans wc2 on wc2.war_id = w.id and wc2.id <> wc.id\r\n\t\tjoin war_clan_members wcm2 on wcm2.war_clan_id = wc2.id and wa.defender_tag = wcm2.tag\r\n\twhere\r\n\t\twc.tag in ($clans)\r\n\t\tand (wcm.tag in (select tag from @latest_members) or '$onlycurrentmembers' = 'No' and wcm.tag in ($players))\r\n\t\tand $__timeFilter(w.end_time)\r\n\tgroup by\r\n\t\twcm2.town_hall_level - wcm.town_hall_level\r\nend\r\n\r\nselect\r\n\ttownhall_diff as 'Townhall diff',\r\n\tsum(total_destruction) / cast(sum([count]) as float) as 'Destruction'\r\nfrom\r\n\t@attack_table\r\ngroup by\r\n\ttownhall_diff\r\norder by\r\n\ttownhall_diff asc"
      }
     ]
    }
   ]
  }
 ]
}